### ISSUE TITLE
Parse Yokogawa data with overlap

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#10]
When parsing grids of yokogawa data with overlap, let's move the individual tiles such that there is no overlap.

The only thing we will initially support are grids with regular overlap. Thus, we can calculate the shift that will be necessary and ensure that the overlap is regular after metadata parsing. 

See https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/15 for detailed discussion of how we handle overlap and https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/11 for an overview of the image data modalities. This is modality # 2: Grid imaged with overlap

**Comment by jluethi** [comment]
The next thing to be done here is that we get a reasonable, small, real-world test set to check whether the current implementation already works. I've seen that it fails when there is some non-regular overlap (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/110). That's fine, because that's the current scope. I wonder though whether with the 1 pixel shifts, this actually won't hold up as well and also run into this error by chance?
=> to be tested! :) Maybe it already works well, we need to get a fitting dataset @gusqgm :)

**Comment by gusqgm** [comment]
Hey there!
just added information on this test dataset. It has 50 pixel overlap between FOV's, so it will be interesting to test run it and see if Fractal manages to put FOV's side by side. more information can be found in the [list](https://github.com/fractal-analytics-platform/fractal/issues/213). Curious to see its output!

**Comment by jluethi** [comment]
This is working well now. Fractal parses images with overlap, moves them so that they are just next to each other, but keeps track of the original positions in the FOV_ROI table.

See here for the example of this running for the dataset mentioned above: https://github.com/fractal-analytics-platform/fractal-demos/tree/fb71f0e03b77eb7d6ada92e42e7674c9cf64375e/examples-v1/17_Overlap

It then looks like this (a small shift between the two FOVs because we imaged with overlap):
![Ome_Zarr_overlap_zoom_in](https://user-images.githubusercontent.com/18033446/207388160-9b632495-51d7-4f07-86ec-1ede1eed0e40.png)

Or like this as an overview:
![Ome_zarr_overlap_overview](https://user-images.githubusercontent.com/18033446/207388273-d685a4b1-b10b-4232-b3fc-38dcc470f142.png)
