### ISSUE TITLE
Use ID-matching when defining ROIs

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#102]
Branching from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/100

**Comment by jluethi** [comment]
If the new fixes lead to correct arrangements for both the 5x5 grid in the 10 well case, as well as correct display of the search-first data, then let's postpone this issue until we hit the first other microscope (e.g. the Molecular Devices at FMI) to get a better idea how much the input data structure will vary.

**Comment by tcompa** [comment]
Notice that the mlf file also includes the filenames. When we refactor metadata_parsing (ref #94), in principle we could also output the list of filenames. This would avoid looking for filenames via glob, which in general is a good idea. And the ID-matching would then be automatically taken care of, since the FOV list and the filenames are sorted in the same way (as they come from the same lines of the XML file).

This would also make other metadata-less use cases (#14, #47) a bit more complex, but probably not too much: on top of generating a "fake" metadata table, we would also need to glob the image files and sort them correctly (as we already do).

Let's think about it, especially during #94.

**Comment by jluethi** [comment]
After the discussion today: We should consider whether aggregating per FOV is really what we want for the metadata or whether we provide some grouped table that contains a single row per image.

**Comment by jluethi** [comment]
Interesting idea, but not a current priority
