### ISSUE TITLE
Use `/` zarr separator in MIP

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#112]

**Comment by jluethi** [comment]
Are we checking for anything regarding the Zarr structure in any of our tests? Would be great to add a test otherwise to check that the structure doesn't change. I.e. that we get the expected number of chunked files, in the expected folder structure.

**Comment by jluethi** [comment]
Also, conceptually, the `.` separator appears to be better supported now than in the past :) At least some napari visualization with it are still working, e.g. in the 23 well case.

**Comment by tcompa** [comment]
Fixed in https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/114
I'll merge and release as soon as the (updated) CI passes

**Comment by tcompa** [comment]
Fixed in `0.1.9`
