### ISSUE TITLE
Review MIP task: make it work by ROI? Make it work at the whole-plate level?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#115]
The MIP task currently works on the entire zarr array, because it is not based on any per-FOV processing.

For optimization purposes, we can decide to make it work on the available FOV ROIs only. If the array of FOVs is very sparse, there could be a significant advantage time-wise.

EDIT: this is to be assessed carefully, because at the moment it is written in a way which is quite optimized for dask to handle all the whole array at the same time, while per-ROI processing would scan ROIs sequentially.

**Comment by tcompa** [comment]
Based on last week meetings, and related to https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/279#issuecomment-1637522831, there is also the possibility of going the opposite way: instead of moving towards per-ROI operations, could we move away from the pair of prepare&fill tasks and simply have an MIP task that does everything at the plate level? It would be an expensive task, that's for sure, but it probably would play well with internal (dask multithreading) parallelization. It's true however that splitting on multiple nodes is useful in terms of memory.

To be discussed, and/or tested with some real data.

The obvious benefit would be simplifying the user flow (one MIP task, instead of a pair of fill&prepare tasks), but we should make sure that this scales decently with the dataset size.

**Comment by jluethi** [comment]
> It would be an expensive task, that's for sure, but it probably would play well with internal (dask multithreading) parallelization.

Let's test it on some real data. We could add max projection functionality to the data copying in the copy ome zarr task (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/279) and then compare the performance. For most cases, that is probably the best way to go. We can then test on the 23 well dataset (1TB 3D images) and on some other 384 well datasets. I could also imagine that we may want to keep the option to do MIP per well (but not per ROI, I'd agree here), but not encourage it by default

**Comment by tcompa** [comment]
Closing in favor of #558 (which goes in the opposite direction, that is, trying to fully remove ROIs from the MIP task)
