### ISSUE TITLE
Stitching of images with overlap

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#116]
Let's use this task to discuss stitching of images with overlap, see modality 2 in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/11#issuecomment-1261838969

**Comment by gusqgm** [comment]
As mentioned in #10 , I have added a dataset for testing this with 50 pixel overlap. Let's discuss here which ways we could best approach this challenge.

**Comment by jluethi** [comment]
After discussions with Clara about this topic, I think stitching can be in the backlog for the moment. It's unclear whether she will continue to image with overlap in her project. Thus, until this is clearer or someone else is pushing for actual stitching, I'd say we keep this issue on hold.

**Comment by jluethi** [comment]
We are not planning to cover this in fractal-tasks-core. The multi-view stitcher could be a good solution for this: https://github.com/multiview-stitcher/multiview-stitcher
