### ISSUE TITLE
[docs] Auto-generate documentation (hosted on readthedocs)

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#129]
Let's pick a documentation mode that we'll use and which can be auto-generated from the docstrings

**Comment by tcompa** [comment]
See https://fractal-tasks-core.readthedocs.io for a preliminary version, by @mfranzon and me.

An example:
![Screenshot from 2022-10-19 13-06-04](https://user-images.githubusercontent.com/3862206/196674585-1ada1a40-bbc3-46fd-a9b9-f3f5b0b1267d.png)

**Comment by tcompa** [comment]
Note that a basic style guide for docstrings is available in `docs/README.md`.
