### ISSUE TITLE
Remove rows & cols parameter from yokogawa to Zarr

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#13]
To support search-first, we move away from the logic of wells consisting of rows & columns of images. Given the metadata parsing (https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/25), we now know the position of each field of view (in physical units that are relative to the center of the acquisition position, e.g. going from ~ -1000 to around +1000 in x & y in our examples).

We can use this positional metadata to decide where each FOV is placed in the well zarr array and how large the well zarr array should be (combination of position, pixel sizes & image dimensions in pixels). Thus, we should be able to handle the parsing of our existing test sets without needing row & column information.

If we generalize that, it will be a much smaller step towards the full parsing of search first data (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/8). Plus it reduced the inputs a user needs to provide.

**Comment by jluethi** [comment]
@mfranzon where are we at with this?

Big picture, we mostly want to parse the position from the metadata table whenever it is available. There is also the idea here as 3): https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/47
> The somewhat simple case of full rectangular wells (like most of our test cases so far). Based on very few parameters (pixel sizes, bit depth, grid dimensions & image sizes), we can calculate all the metadata parameters for this simple case without needing metadata files or dataframes.

Goals:
1) Parse positions based on metadata
Later: Optionally parse with rows & cols parameters. If it's easy to keep optional support while building the default for parsing from metadata, then let's do that (would simplify using some of the larger test cases where it's hard to generated the correct metadata). If not, let's drop rows & cols, just build the metadata table based parsing and worry about adding this functionality later.

**Comment by mfranzon** [comment]
Hi! Sorry for the delay, unfortunately I started just today working on this. Here is the first commit, which is not working, but not far away from the solution. What is missing is the delayed handling of the image loading and changing the stack along z-index.
I hope to close it during the day.
 ad458c9c8505fd1dd3b80cd4b3794bcca27d27da

**Comment by tcompa** [comment]
work in progress by @mfranzon:

![Screenshot from 2022-09-14 09-55-05](https://user-images.githubusercontent.com/3862206/190096121-359438a5-74b1-4844-be4b-eb75449cc5b9.png)
![Screenshot from 2022-09-14 09-55-38](https://user-images.githubusercontent.com/3862206/190096162-fb0cb573-7ef5-4b40-af98-874fae7cf553.png)

At the moment the final zarr file has roughly the same size as the original one (that is, the zeros are not actually stored on disk)

**Comment by tcompa** [comment]
There is now some example in `examples/02_cardio_tiny_dataset_sparse`, producing output similar to the one in the previous comment.

**Comment by tcompa** [comment]
Closed with #80 and #79
