### ISSUE TITLE
Set standard task interface

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#133]
The `__name__ == "__main__"` block of tasks is most often out-of-date.
To use tasks in https://github.com/fractal-analytics-platform/fractal-server/issues/132, it needs to be fixed.

**Comment by tcompa** [comment]
- [ ] dummy.py
- [ ] dummy_fail.py
- [ ] create_zarr_structure.py
- [ ] yokogawa_to_zarr.py
- [ ] illumination_correction.py
- [ ] cellpose_segmentation.py
- [ ] measurement.py
- [ ] replicate_zarr_structure.py
- [ ] maximum_intensity_projection.py

**Comment by tcompa** [comment]
Note that this also requires passing dictionary arguments from the command line. Since this is not a very smooth, let's postpone major changes based on this issue until the new server structure is better defined.

**Comment by jluethi** [comment]
Hmm, ok. Could we not parse arguments explicitly using `argparse.ArgumentParser` anymore afterwards? Also, could they still be parsed as the json file then?

For simple inputs, e.g. which executor to use, it's nice to directly do this on the command line. More complex inputs, e.g. channel infos, illumination correction info etc., defaulting to using json files for them would be nice.

**Comment by tcompa** [comment]
> Hmm, ok. Could we not parse arguments explicitly using `argparse.ArgumentParser` anymore afterwards? Also, could they still be parsed as the json file then?

Yes, argparse is already the approach we use to parse arguments, but that section is probably outdated in the current version of most tasks.

> For simple inputs, e.g. which executor to use, it's nice to directly do this on the command line. More complex inputs, e.g. channel infos, illumination correction info etc., defaulting to using json files for them would be nice.

Yes, that's the plan.

**Comment by tcompa** [comment]
An update, based on ongoing work on the server side.

The expected interface to be compatible with fractal-server v1 is similar to [this one](https://github.com/fractal-analytics-platform/fractal-server/blob/7199276b540a40eef0e494e0939d87e25e1bb4b5/fractal_server/tasks/dummy.py#L108-L158).
This allow the task to be called like
```
/path/to/python /path/to/task/module.py -j /some/path/to/args.json --metadata-out /some/path/to/output/metadata.json
```
We now need to turn the code block linked above into a standard function (which does not depend on the specific parameters of each task), introduce it into all tasks, and test that the tasks are correctly called.

NOTE: the json file in `-j` is **not** the one where a certain argument will be, but the one where **all** arguments will be.

**Comment by jluethi** [comment]
Sounds like a good plan!

**Comment by tcompa** [comment]
The basics are already there in #155, for a couple of tasks (and within a test).
Then we'll need to copy this over to all tasks, and see how it matters for #151
