### ISSUE TITLE
Parsing Yokogawa data with pandas table as metadata inputs

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#14]
There are 3 main ways to parse the metadata for a Yokogawa dataset:

1. The dataset has the MeasurementData.mlf and MeasurementDetail.mrf, it's being parsed to define ROIs. (our current implementation)
2. The user creates their own pandas table that follows the same specification (very useful to allow users with special cases a path into Fractal)
3. The somewhat simple case of full rectangular wells (like most of our test cases so far). Based on very few parameters (pixel sizes, bit depth, grid dimensions & image sizes), we can calculate all the metadata parameters for this simple case without needing metadata files or dataframes. => https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/47

This issue describes case 2

---

Our current parsing method for the yokogawa relies on the MeasurementData.mlf & the MeasurementDetail.mrf file. Those are parsed to define the ROIs (see here: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/25) and we generate a table like this:
![Screenshot 2022-07-21 at 17 11 33](https://user-images.githubusercontent.com/18033446/180249169-a4065454-1c52-41fa-8781-8e7657338208.png)

From that table, the relevant metadata is then assigned to each ROI and ROIs get coordinates assigned (that are saved to the AnnData table per well).

We should create a second parsing function (/an alternative input to the parsing function) that allow users to pass a pandas dataframe (either pass a dataframe or pass a path to a csv file) directly to the parsing function, such that it takes this table & assigns ROIs based on the table.

Testcase TBD. I will create a test case for the single-well, 2x2 scenario

**Comment by jluethi** [comment]
Let's reassess this based on how the table may change. One idea is to parse filenames from the metadata file as well to make parsing more robust. This would make this idea harder to implement.

**Comment by tcompa** [comment]
- [ ] Allow two usage modes: either reading mlf/mrf files or passing a csv path to `site_metadata`.
- [ ] Fail otherwise

Note: this is **not** related to https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/47.
