### ISSUE TITLE
[napari-workflows] Handling of dataframe output

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#142]
In the current version, at the end of a napari-workflow computation we do the following to handle all outputs of "dataframe" type:
```python
    # Output handling: "dataframe" type (for each output, concatenate ROI
    # dataframes, clean up, and store in a AnnData table on-disk)
    # FIXME: is this cleanup procedure general?
    for (name, params) in dataframe_outputs:
        table_name = params["table_name"]
        list_dfs = output_dataframe_lists[name]
        # Concatenate all FOV dataframes
        df_well = pd.concat(list_dfs, axis=0)
        # Extract labels and drop them from df_well
        labels = pd.DataFrame(df_well["label"].astype(str))
        df_well.drop(labels=["label"], axis=1, inplace=True)
        # Convert all to float (warning: some would be int, in principle)
        measurement_dtype = np.float32
        df_well = df_well.astype(measurement_dtype)
        # Convert to anndata
        measurement_table = ad.AnnData(df_well, dtype=measurement_dtype)
        measurement_table.obs = labels
        # Write to zarr group
        group_tables = zarr.group(f"{in_path}/{component}/tables/")
        write_elem(group_tables, table_name, measurement_table)
```

This was ported from our current `measurement` task (and simply put within a loop, cause there may be more outputs of this kind).

How should we proceed? Is this apprach (concatenating the per-ROI dataframes, and handling them in this way) general, or should we have different paths?

**Comment by jluethi** [comment]
Hmm, we may need to consider the relabeling part. Other than that, I think a first default can be that everything is saved per well. Once we use this a bit more, let's reevaluate whether other options of storing tables will also come up.

**Comment by jluethi** [comment]
Ok great! If on-the-fly relabeling works well, that seems like a nice approach to me!

**Comment by tcompa** [comment]
Closing in favor of #138, I will re-open if needed
