### ISSUE TITLE
Check types for task-argument validator

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#173]
Caveats:
1. This issue has nothing to do with the actual task content, but it's rather about their fractal interface.
2. This feature is optional, and e.g. one we would not use during new-task development (where the set of arguments changes frequently).

----

In the standard task interface, each task file ends with a block like
```python
if __name__ == "__main__":
    from pydantic import BaseModel
    from fractal_tasks_core._utils import run_fractal_task

    class TaskArguments(BaseModel):
        input_paths: Sequence[Path]
        output_path: Path
        metadata: Dict[str, Any]
        component: str
        delete_input: bool = False

    run_fractal_task(task_function=yokogawa_to_zarr, TaskArgsModel=TaskArguments)
```

`TaskArgsModel` is an optional argument for `run_fractal_task`, but it is quite useful to pass it because then `pydantic` validates all types of arguments before even entering the task. This means we could enforce some specific constraints on the inputs (not only types, but also e.g. allowed values for some flags), and passing some invalid arguments will fail in a reasonable way (something like a `ValidationError`, and not some random `RuntimeError` or `IndexError` just because some argument was wrong).

This, however, introduces a bit of friction when writing tasks:
1. We need to add all type hints to the function.
3. We need to duplicate these hints in the `TaskArguments` class, which we will sometimes forget to do (e.g. if we add a new argument to a task).

As of 1, I see no problem since here we are looking at the core tasks, which are worth some extra work. Also: it's useful to get a nice documentation

As of 2, let's add a test that verifies the correct setup in the CI - so that we are sure we are never forgetting some arguments. The relevant code should look like:
```python
from typing import get_type_hints
from typing import Optional
from typing import Dict
from typing import Any
from pydantic import BaseModel

def task_function(arg1: str, arg2: int = 1, arg3: int = None) -> Dict[str, Any]:
    return 1

class TaskArguments(BaseModel):
    arg1: str
    arg2: int
    arg3: Optional[int] = None

hints_task = get_type_hints(task_function)
if "return" in hints_task:
    hints_task.pop("return")
hints_args = get_type_hints(TaskArguments)
print(hints_task)
print(hints_args)
assert hints_task == hints_args
```

**Comment by jluethi** [comment]
> TaskArgsModel is an optional argument for run_fractal_task, but it is quite useful to pass it because then pydantic validates all types of arguments before even entering the task. 

This sounds great! Optional as in we don't need to have it in development or in a user-defined task in the beginning. But a great way for our stable tasks to check they are getting valid inputs.

> We need to add all type hints to the function.

Reasonable trade-off to me and good for code quality

> We need to duplicate these hints in the TaskArguments class, which we will sometimes forget to do (e.g. if we add a new argument to a task).

Can we have a way to tell Fractal to ignore type hints? If a user in a production setup runs into a bug/edge-case of needing to run a type of input that will work, but which we didn't consider before, there should be some way to "force" the task to run anyway (to not do the pydantic check), without having to wait for a task to be updated. If that's possible (and off by default), then I think this is  a great approach!

**Comment by tcompa** [comment]
> Can we have a way to tell Fractal to ignore type hints? If a user in a production setup runs into a bug/edge-case of needing to run a type of input that will work, but which we didn't consider before, there should be some way to "force" the task to run anyway (to not do the pydantic check), without having to wait for a task to be updated. If that's possible (and off by default), then I think this is a great approach!

I see your point, but I think we should not do that (at least for now).

It is straightforward to switch on/off the validation from within the task, but our tasks have to run through fractal-server. This means adding a `validate_output` attribute to all tasks, and handling it in the server, so that it can be then passed to the task when they run.

IMO the benefits of this approach (allowing a user to hack the intended interface of a task) are not enough to justify this additional complexity.

My take is rather that for (each task) we either validate input or we don't:
* We do validate input for tasks which we consider well crafted and robust, and we do not allow any unintended use. If we discover a new way to use these tasks, we need to make a new release (or to install a custom version).
* We do not validate input (or we include some catch-all type hints like `Any`) for tasks that are under development, or for tasks where we feel there could be unexpected use cases.

**Comment by tcompa** [comment]
Small addendum: at least for core-tasks, I think we will need (at some point) a careful review of all current arguments/interface. This will include a careful check of all type hints.

(see related upcoming issue on fractal-default arguments)

**Comment by tcompa** [comment]
I am merging https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/175, that implements the required feature from the first comment here.

Let's close the issue if/when we are also happy with the rest of the discussion.

**Comment by jluethi** [comment]
> We do validate input for tasks which we consider well crafted and robust, and we do not allow any unintended use. If we discover a new way to use these tasks, we need to make a new release (or to install a custom version).

Ok, I can live with that. We'll also build the option for custom tasks anyway, so worst case, a user could make a custom version of a task that can handle their input. That should be contributed back to the repo if it's generally reasonable, but there is a way for users to progress even if the update cycle in production slows down :)
