### ISSUE TITLE
Image filename parsing assumes date case in wrong case

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#189]
I'm trying to process the search-first zebrafish test case and created a subset of the data that doesn't have any overlap issues. In this subset, something in the `lib_parse_filename_metadata.py` fails during the `parse_filename` call.

The test data is here: `/data/active/fractal/3D/PelkmansLab/zebrafish_subset/`
<details>
<summary> Here is an example_run.sh script </summary>

```
# For the demo: Run everything as the current user
USERNAME="$(whoami)"
PORT=8001
echo -e "FRACTAL_USER=$USERNAME@me.com\nFRACTAL_PASSWORD=test\nFRACTAL_SERVER=http://localhost:$PORT" > .fractal.env

###############################################################################
# THINGS TO BE CHANGED BY THE USER
# Adapt to settings to where you run the example
BASE_FOLDER_EXAMPLE="/data/homes/$USERNAME/03_fractal/fractal-demos/examples"
###############################################################################


LABEL="zebrafish_subset_test2"

###############################################################################
# IMPORTANT: modify the following lines, depending on your preferences
# 1. They MUST include a `cd` command to a path where your user can write. The
#    simplest is to use `cd $HOME`, but notice that this will create many sh
#    scripts in your folder. You can also use `cd $HOME/.fractal_scripts`, but
#    first make sure that such folder exists
# 2. They MAY include additional commands to load a python environment. The ones
#    used in the current example are appropriate for the UZH Pelkmans lab setup.
TARGET_DIR=~/.tmp_fractal
rm -r $TARGET_DIR
mkdir $TARGET_DIR
WORKER_INIT="\
export HOME=$HOME; \
cd $TARGET_DIR; \
source /opt/easybuild/software/Anaconda3/2019.07/etc/profile.d/conda.sh; \
conda activate /data/homes/fractal/sharedfractal; \
"
###############################################################################

# Set useful variables
PRJ_NAME="proj-"$USERNAME"-"$LABEL
DS_IN_NAME="input-ds-"$USERNAME"-"$LABEL
DS_OUT_NAME="output-ds-"$USERNAME"-"$LABEL
WF_NAME="WF-2x2-"$USERNAME"-"$LABEL

# Set cache path and remove any previous file from there
export FRACTAL_CACHE_PATH=`pwd`/".cache"
rm -v ${FRACTAL_CACHE_PATH}/session
rm -v ${FRACTAL_CACHE_PATH}/tasks

# Define/initialize empty project folder and temporary file
PROJ_DIR=$BASE_FOLDER_EXAMPLE/tmp_${LABEL}
rm -r $PROJ_DIR
mkdir $PROJ_DIR
TMPJSON=${PROJ_DIR}/tmp.json

###############################################################################
# IMPORTANT: modify the following lines so that they point to absolute paths
INPUT_PATH="/data/active/fractal/3D/PelkmansLab/zebrafish_subset/"
OUTPUT_PATH='/data/active/jluethi/Fractal/20221107-zebrafish-subset/'
###############################################################################

# Define useful auxiliary command (this will be removed in the future)
CMD_JSON="python aux_extract_id_from_project_json.py $TMPJSON"

# Create project
fractal -j project new $PRJ_NAME $PROJ_DIR > $TMPJSON
PRJ_ID=`$CMD_JSON project_id`
DS_IN_ID=`$CMD_JSON dataset_id "default"`
echo "PRJ_ID: $PRJ_ID"
echo "DS_IN_ID: $DS_IN_ID"

# Update dataset name/type, and add a resource
fractal dataset edit --name "$DS_IN_NAME" -t image --read-only $PRJ_ID $DS_IN_ID
fractal dataset add-resource -g "*.tif" $PRJ_ID $DS_IN_ID $INPUT_PATH

# Add output dataset, and add a resource to it
DS_OUT_ID=`fractal --batch project add-dataset $PRJ_ID "$DS_OUT_NAME"`
fractal dataset edit -t zarr --read-write $PRJ_ID $DS_OUT_ID
fractal dataset add-resource -g "*.zarr" $PRJ_ID $DS_OUT_ID $OUTPUT_PATH

# Create workflow
WF_ID=`fractal --batch task new "$WF_NAME" workflow image zarr`
echo "WF_ID: $WF_ID"

# Add subtasks

echo "{\"num_levels\": 5, \"executor\": \"cpu-low\", \"coarsening_xy\": 2, \"channel_parameters\": {\"A01_C01\": {\"label\": \"Channel 1\",\"colormap\": \"00FFFF\",\"start\": 110,\"end\": 700 }, \"A02_C02\": {\"label\": \"Channel 2\",\"colormap\": \"FF00FF\",\"start\": 110,\"end\": 1500 }, \"A03_C03\": {\"label\": \"Channel 3\",\"colormap\": \"FFFF00\",\"start\": 110,\"end\": 1500 }}}" > ${PROJ_DIR}/args_create.json
fractal task add-subtask $WF_ID "Create OME-ZARR structure" --args-file ${PROJ_DIR}/args_create.json

echo "{\"executor\": \"cpu-mid\"}" > ${PROJ_DIR}/args_yoko.json
fractal task add-subtask $WF_ID "Yokogawa to Zarr" > ${PROJ_DIR}/args_yoko.json

echo "{\"executor\": \"cpu-low\"}" > ${PROJ_DIR}/args_replicate.json
fractal task add-subtask $WF_ID "Replicate Zarr structure" --args-file ${PROJ_DIR}/args_replicate.json

echo "{\"executor\": \"cpu-low\"}" > ${PROJ_DIR}/args_mip.json
fractal task add-subtask $WF_ID "Maximum Intensity Projection" --args-file ${PROJ_DIR}/args_mip.json

# echo "{\"labeling_level\": 2, \"executor\": \"cpu-low\", \"ROI_table_name\": \"well_ROI_table\"}" > ${PROJ_DIR}/args_labeling.json
# fractal task add-subtask $WF_ID "Cellpose Segmentation" --args-file ${PROJ_DIR}/args_labeling.json

# echo "{\"level\": 0, \"measurement_table_name\": \"nuclei\", \"executor\": \"cpu-low\", \"ROI_table_name\": \"well_ROI_table\",\"workflow_file\": \"$BASE_FOLDER_EXAMPLE/03_cardio_dataset_one_2x2_well_3_channels_10_Z/regionprops_from_existing_labels_feature.yaml\"}" > ${PROJ_DIR}/args_measurement.json
# fractal task add-subtask $WF_ID "Measurement" --args-file ${PROJ_DIR}/args_measurement.json

# Apply workflow
fractal task apply $PRJ_ID $DS_IN_ID $DS_OUT_ID $WF_ID --worker_init "$WORKER_INIT"
```

</details>

It fails here: https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/bd0408455de8c6447dc4216344ef2a765356643d/fractal_tasks_core/lib_parse_filename_metadata.py#L69

With the following error message:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 782, in _unwrap_futures
    kwargs[key] = dep.result()
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 288, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/parsl/dataflow/dflow.py", line 483, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/parsl/app/errors.py", line 137, in reraise
    reraise(t, v, v.__traceback__)
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/data/homes/fractal/.conda/envs/pelkman_demo_fractalserver/lib/python3.8/site-packages/parsl/app/errors.py", line 175, in wrapper
    return func(*args, **kwargs)  # type: ignore
  File "/data/homes/fractal/sharedfractal/lib/python3.8/site-packages/fractal_server/app/runner/parsl/__init__.py", line 57, in _task_fun
    metadata_update = _callable(
  File "/data/homes/fractal/sharedfractal/lib/python3.8/site-packages/fractal_tasks_core/create_zarr_structure.py", line 167, in create_zarr_structure
    metadata = parse_filename(fn.name)
  File "/data/homes/fractal/sharedfractal/lib/python3.8/site-packages/fractal_tasks_core/lib_parse_filename_metadata.py", line 70, in parse_filename
    raise Exception(
Exception: Failure in metadata parsing of AssayPlate_Greiner_#655090, with img_date={img_date} and img_time={img_time}
```

It appears the filenames run into an issue: 
This is an example filename, it's quiet typical of the Yokogawa, but we didn't have it in the initial test cases:
`AssayPlate_Greiner_#655090_B02_T0001F004L01A01Z01C01.tif`

I would assume the Zarr file would be called `AssayPlate_Greiner_#655090`, which isn't actually a relevant name for the Zarr file. But the way the current parsing works, it assumes this is a barcode reading and then fails.

-----
This bug is quite important, because many people may come with data formatted this way and then our parsing fails!

The high level discussion we should have for this:
How should we handle plate naming in general? Should we 
a) Try to be fancy and create a good plate name from the filename (current), with the risk of failing for some cases we haven't seen (=> then catch those somehow)
b) Just do much simpler parsing, e.g. always just take the string before the _well (e.g. anything before _B02 here). @gusqgm the time parsing idea came from you in the beginning, right? Is it critical?
c) Allow users to name the OME-Zarr file (via an optional input? `AssayPlate_Greiner_#655090` isn't a meaningful name for the Zarr file after all and will actually occur in many settings when users don't change defaults at the microscope).

My intuition is:
Go with b) for a quick-fix, optionally implement either a & c or one of them.

**Comment by jluethi** [comment]
(also, the error message formatting doesn't work anymore, because line 72 is missing the f before the string)

**Comment by jluethi** [comment]
I've looked at the filenames we support more closely here:
```
    Three kinds of filenames are supported:
    1) Filenames from UZH:
       20200812-Cardio[...]Cycle1_B03_T0001F036L01A01Z18C01.png
       with plate name 20200812-Cardio[...]Cycle1
    2) Filenames from FMI, with successful barcode reading:
       210305NAR005AAN_210416_164828_B11_T0001F006L01A04Z14C01.tif
       with plate name 210305NAR005AAN
    3) Filenames from FMI, with failed barcode reading:
       yymmdd_hhmmss_210416_164828_B11_T0001F006L01A04Z14C01.tif
       with plate name RS{yymmddhhmmss}
```

While I didn't spot this on initial implementation (sorry @mfranzon ), these assumptions are clearly to narrow, as this test-case shows. I don't think we can make assumptions on the filename structure based on the number of `_` before the well. We could check whether a filename belongs to some known type and then process that in some fancy way.

But thinking bigger picture: What do we really need this initial processed part for? Is it only to name the OME-Zarr?
In that case, I think we should not do any fancy processing and just name the OME-Zarr by the project name or something like that. The filename could sometimes be useful, but not always. And we anyway already make the user specify a project name.
Alternatively, we could pick the output dataset name as the relevant string of how our OME-Zarr file is named.

Let's briefly discuss this on Wednesday

**Comment by gusqgm** [comment]
This is unfortunate indeed!

The point in b) did not really come from `me` per se, but rather from an error handling of yokogawa once the barcode scanner does not work. If the barcode is not working properly the time_stamp is written instead.
It is an annoying feature but does happen from time-to-time during image acquisitions.

If strictly necessary, we could still go for a quick fix for the time being, but keeping in mind that a more stable solution that can still encompass this possibility of the barcode scanning failure output will eventually need to be found, at least until we have Fractal running in the lab more generally.

**Comment by jluethi** [comment]
Hmm, ok, good to know. Let's discuss then what should happen with these timestamps and this Yokogawa formats. Currently, we parse img_date & img_time, but the function doesn't do anything with them. It just removes them from the OME-Zarr name that is then assigned.

So if there's a broader use-case for them, we don't currently cover this and should think about what should actually happen with this information

**Comment by tcompa** [comment]
For the record, the list of supported filenames was discussed in https://github.com/fractal-analytics-platform/fractal/issues/48 (see also `test_unit_parse_metadata_from_filename.py`). Looking at it after a few months, it doesn't look so robust - agreed.

@jluethi @gusqgm if you let us know a list of intended uses (i.e. filename and expected plate name), we will quickly update it. And while we are at it we can probably also streamline the part of metadata extraction (instead of using all those regex).

> (also, the error message formatting doesn't work anymore, because line 72 is missing the f before the string)

Fixed.

**Comment by jluethi** [comment]
Yokogawa filenames can basically be:
`ANYTHING_B02_T0001F004L01A01Z01C01.tif`
In some cases, the Z position can have more than 2 digits, I have never seen any of the other positions have extra digits (i.e. we can have `ANYTHING_B02_T0001F004L01A01Z125C01.tif`). `ANYTHING` can be any possible string that is valid as part of a filename.

The part starting from B02 has important information we need to extract. The `ANYTHING` part is often just flavor, can either be a default from the microscope, a name the user entered or a readout (successful or failed) from a plate reader.

There's a discussion to be had whether we need to parse the `ANYTHING` part more specifically and what we'd do with this information. So far, we used `ANYTHING` (or a subset of it in the case of the FMI optimized parsing) as the the name for the OME-Zarr file. As far as I'm aware, it's not really used for more (the `plate_prefix`, which is the first string before the first `_` is used in some of the parsing as well though).
Thus, we can discuss whether extra info needs to be extracted from the `ANYTHING` part and what would need to be done with it (I'll discuss this further with Gustavo). As far as the general parsing is concerned, the OME-Zarr file needs to have some name, but it doesn't necessarily need to be part of the filename string. Easiest "quick" fix would be to just have the OME-Zarr name be the `ANYTHING` string. And then we can have a debate on whether it should be the dataset name, project name, additional string, specially parsed version of `ANYTHING` or something different.

**Comment by tcompa** [comment]
OK, then in the meanwhile we can prepare a new function that just splits `ANYTHING_B02_T0001F004L01A01Z01C01` into `ANYTHING` + the set of standard metadata attributes. And then we can decide what to do with `ANYTHING`.

**Comment by jluethi** [comment]
> OK, then in the meanwhile we can prepare a new function that just splits ANYTHING_B02_T0001F004L01A01Z01C01 into ANYTHING + the set of standard metadata attributes. And then we can decide what to do with ANYTHING.

Sounds good, thanks! :)

**Comment by jluethi** [comment]
That's great! With that, we can close this issue. And I'll open a discussion issue about whether we need to do something with potential infos we parse from the filename + how we want to name OME-Zarr files in general. But neither of those questions are urgent.
