### ISSUE TITLE
Associate optional mask to each ROI (in tables), and use it for I/O selection

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#195]
(branching from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/45)

This requires #194

**Comment by jluethi** [comment]
Just to make sure we don't duplicate work here: The optional mask would be the label image. And the association should be possible via the metadata of the ROI table & the obs dataframe of AnnData.
See the proposed OME-Zarr table spec: https://github.com/ome/ngff/pull/64
My understanding is that we'd use the `region_key` in .zattrs to specify which column in the obs dataframe contains the relative path to the label image. For our use case here and the current implementation, each row of the dataframe would point to the same label image (but one could eventually also store e.g. a combined ROI table, where they point to the different label images in the different wells)

**Comment by tcompa** [comment]
Close in favor of #333.
