### ISSUE TITLE
Copy and re-structure tests from fractal

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#2]
We should copy over part of the tests folder from fractal and re-structure it a bit.

- [x] Cleaner structure of tests/data: there should be a few fake png datasets (at least one made of all zeros and one made of all non-zeros), with clean mlf/mrf metadata files. And then there could be a couple of more realistic datasets, possibly accessible through zenodo (see https://github.com/fractal-analytics-platform/fractal/issues/163).
- [x] Only a few of the current fractal tests are meaningful for fractal_tasks_core, and should be copied over. Done.
- [x] There are several `pipeline.py` (or similar) files in `fractal/tasks/Sandbox_*`, which should be transformed into small integration tests.

**Comment by tcompa** [comment]
In order to test labels, in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/86, we need to set up a test where we use the tiny dataset.

**Comment by tcompa** [comment]
Starting from https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/90, test do use real data (the tiny dataset from Zenodo). This is quite close to an integration test: workflows should run until the end, and there is OME-NGFF validation of the results - see e.g. #86.

I'd say that the explicit validation of the actual numbers written in the zarr files is out of scope, for the moment, due to the several upcoming updates to the core tasks.

**Comment by jluethi** [comment]
Sounds good, great to have those workflow tests for the moment. Once tasks stabilize a bit further, we can add some tests on tiny datasets to check the actual data. Plus move most tests to their tasks to ensure tasks do what we expect them to do :)
