### ISSUE TITLE
Measurement upscaling can run into shape mismatch (probably rounding issue)

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#201]
When running the search-first CV8K test dataset and using a label image from level 2 to get measurements, we run into this upsampling error:

```
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.3.2/venv/lib/python3.8/site-packages/fractal_tasks_core/measurement.py", line 224, in <module>
    run_fractal_task(task_function=measurement, TaskArgsModel=TaskArguments)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.3.2/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 80, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.3.2/venv/lib/python3.8/site-packages/fractal_tasks_core/measurement.py", line 119, in measurement
    raise Exception(
Exception: ('Error in dapi/label array shapes (after upscaling)', (1, 8404, 8114), (1, 8404, 8112))

```

The example is available here and is a nice, small test set: https://github.com/fractal-analytics-platform/fractal-demos/tree/main/examples-v1/15_CV8K_Test
(Search first test case 7 here: https://github.com/fractal-analytics-platform/fractal/issues/213)

This may also be the case that some other measurements on search first data failed, but I couldn't trace back the error there (1.x server to the rescue!)

It's a search-first dataset where FOVs aren't placed in a regular grid, thus the upsampling may be more likely to run into this off-by-2 (or off by fairly little) issue:
![Screenshot 2022-11-14 at 17 26 29](https://user-images.githubusercontent.com/18033446/201716332-a9d9f6b7-de7b-4420-a85f-f8521f5e44a9.png)

**Comment by tcompa** [comment]
Before we review this in detail, is the source of the error already clear to you? That is, what are those two shapes (`(1, 8404, 8114)` and `(1, 8404, 8112)`), and whether one of the two is "correct".

Side comments:
1. Any reason to use `measurement` instead of `napari_workflows_wrapper`? My guess is that we will deprecate the former, at some point.
2. In case we should review this, could you also upload the `Parameters` folder? Thanks.

**Comment by jluethi** [comment]
> Before we review this in detail, is the source of the error already clear to you? That is, what are those two shapes ((1, 8404, 8114) and (1, 8404, 8112)), and whether one of the two is "correct".

I haven't done a deep dive yet, but I have a strong suspicion: 
(1, 8404, 8114) is the real dimension of the bounding box for the well (for this search-first case). In the grid case, the well would have very predictable sizes and they were often divisible by 2. But in the search first case, we can have any size of the well, just depends on the metadata.
The pyramid was created on level 2. Downsampling 8114 by 4 is 2028.5 => doesn't evenly divide. I assume this was rounded down to 2028 and when that was upsampled 4x, we got 8112.

Thus, we'll need to add a test for such a case and decide how we handle upsamplinging in these "off-by-a-few" cases. To make our workflows work easily, we'd need to get back to the exact shape the full res data is in.
One way to achieve this would be 0 padding. Not sure whether there is a better way? 0 padding could also be problematic, because some measurements quantify whether an object touches the edge of an image, which would be lost here... But I don't have a better idea than 0 padding atm

> Any reason to use measurement instead of napari_workflows_wrapper? My guess is that we will deprecate the former, at some point.

The `napari_workflows_wrapper` wasn't registered as a task yet, because wasn't in init, right? Was wondering about that as well though, super happy to switch over to napari workflows :)

> In case we should review this, could you also upload the Parameters folder? Thanks.

Oh right, will push this to make the example complete.

**Comment by tcompa** [comment]
> > Any reason to use measurement instead of napari_workflows_wrapper? My guess is that we will deprecate the former, at some point.
> 
> The `napari_workflows_wrapper` wasn't registered as a task yet, because wasn't in init, right? Was wondering about that as well though, super happy to switch over to napari workflows :)

Good point ;)
This is now available in `fractal-tasks-core=0.3.3` (tests are welcome).

**Comment by jluethi** [comment]
Just ran into this bug again for the 500 GB dataset of Nicole during the measurements. It's also a search-first example, so makes sense that we'd hit that here too. One more place to test once we have a fix

```
2022-12-01 18:57:20,521; WARNING; Input dapi_img has shape (1, 13747, 18200) but expected_dimensions=3
2022-12-01 18:57:20,521; INFO; Prepared input with name='dapi_img' and params={'type': 'image', 'channel': 'A04_C01'}
2022-12-01 18:57:20,521; INFO; input_image_arrays={'dapi_img': dask.array<getitem, shape=(1, 13747, 18200), dtype=uint16, chunksize=(1, 1080, 1280), chunktype=numpy.ndarray>}
Traceback (most recent call last):
  File "PATH/fractal_tasks_core/napari_workflows_wrapper.py", line 570, in <module>
    run_fractal_task(
  File "PATH/fractal_tasks_core/_utils.py", line 89, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "PATH/fractal_tasks_core/napari_workflows_wrapper.py", line 241, in napari_workflows_wrapper
    input_label_arrays[name] = upscale_array(
  File "PATH/fractal_tasks_core/lib_upscale_array.py", line 91, in upscale_array
    raise Exception(f"{info} {upscaled_array.shape=}.")
Exception: Trying to upscale from array_shape=(1, 6873, 9100) to target_shape=(1, 13747, 18200), acting on axis=[1, 2]. Upscale factors: {1: 2, 2: 2} upscaled_array.shape=(1, 13746, 18200).
```

**Comment by tcompa** [comment]
My understanding:

FOVs:
* Each FOV has a specific size (in physical units), which is commensurable with the pixel sizes. In other words, each FOV is made of an integer number of pixels along each direction (x, y, z). Let's say that a FOV column has shape 10x10x10.
* FOVs can be placed in arbitrary positions, but that does not change their shape (which is encoded both in the `.zarray` files and implicitly in the FOV AnnData table).

Images (AKA collections of FOVs):
* For us, at the moment, an OME image is a collection of many FOVs. The position of these FOVs is arbitrary (that is, they are not necessarily placed on a grid), and for instance we could have FOV1 going from x=0 to x=9 (in pixels) and FOV2 going from x=11 to x=20. This would lead to an image shape of [21,10,10], with the slice x=10 filled with zeros. This image shape is not commensurable with the coarsening factor (or with some power of it).
* If the shape of an image is not commensurable with the coarsening factor (or some of its powers), then creating the pyramid with `trim_excess=True` leads to incommensurability issues. This happens in the current example when going from level 1 to level 2:
```
level 0: 10x10x10
level 1: 5x5x10
level 2: 2x2x10
```
This behavior is currently fully allowed (it does not even raise a warning).


@jluethi  I understand that the proposed change would be to pad an image with zeros (at its boundaries, I'd guess). Could you spell it out a bit more in detail? Is it something like this below?
1. Upon building a pyramid, check in advance whether all of the resolution level may be build without trimming.
2. If the check passes, nothing changes (but we are still removing `trim_excess=True` from the code).
3. If the check fails:
    * Modify the 0-th level (which is already stored on disk), by enlarging the X and Y sizes as much as needed to make the shape a multiple of `coarsening_xy**(number of levels)`. Re-write the array to disk (can we do this efficiently, without actually reading and rewriting the whole array just to modify its boundaries? to check)
    * Build the pyramid as you would normally in point 2.
4. Downstream, we (should) always use ROI tables to address parts of the zarr array, and no ROI table will include the area that was just added to the array. Therefore it should never be touched during processing (an exception is https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/115, but it doesn't look like a problem).

What are the issues with this solution?
5. "some measurements quantify whether an object touches the edge of an image, which would be lost here..."
6. Others?

**Comment by jluethi** [comment]
> FOVs can be placed in arbitrary positions, but that does not change their shape (which is encoded both in the .zarray files and implicitly in the FOV AnnData table).

The FOVs are not encoded in the .zarray file, right? The .zarray file just contains information about the image, which is a combination of FOVs. If it's a simple grid, then all the parts of the image have content. In the search first case, there's a bounding-box image and FOVs are placed at different places within it.

----

The summary seems otherwise correct to me. There are 2 ways of approaching this:
1. Changing level 0 to avoid incommensurability issues (as you've described)
2. Changing the upscaling function to handle incommensurability issues

Upside of 1) is that we never need to worry about it, if we know all the pyramids beforehand. 
But we can have things like an image with 5 pyramid levels and creating a segmentation at level 2 also with 5 pyramid levels (=> now 7 overall levels). Also, we will have some tasks that start modifying the size of the image, primarily the registration issues.
Finally, I'm very hesitant to introduce extra 0s or padding to the full-res data, as that is the "real", ground-truth data we have. 
The ROI approach you describe in 4) mostly avoids this problem, but I don't think it would work. i.e. if we want to give an image to napari workflows, we upscale the label image to say 12x12x10. But the actual intensity image just contains 10x10x10 (with 0 paddings to make it 12x12x10) => we'd have to load the 12x12x10 to give to napari workflows to avoid this error, no?


2) Doing it during upscaling seems more reasonable to me. i.e. whenever we upscale, we take the target size of the image and, if necessary, 0-pad the upscaled image.
We need to do this on the fly. Benefit is though that the image that gets some "inaccuracy" introduced is the upscaled image, i.e. the image that we had saved at low resolution and thus anyway wouldn't expect to be full res.

=> I'd be in favor of scenario 2, but maybe I have not thought about some limitations here. Happy to chat about this if we want to discuss this further.

**Comment by tcompa** [comment]
> The FOVs are not encoded in the .zarray file, right?

Of course, my bad (I was writing the comment differently, and this is just a leftover).

**Comment by tcompa** [comment]
#251 includes a first implementation of zero padding within the `upscale_array` function.
The padding behaves as expected, in a unit test.

I also added this feature in the napari-workflows wrapper would work, but we need to test it more carefully (and I don't have an actual test/example immediately available).

**Comment by jluethi** [comment]
UZH data is here: /data/active/fractal/Liberali/20221103_SFtestCV8000/CV8K_images
and it's a small test set with just 66 images

**Comment by tcompa** [comment]
OK, then I will merge #251 and release 0.6.1, to make testing simpler.

**Comment by tcompa** [comment]
Re-opening, waiting for real-life tests.

**Comment by jluethi** [comment]
I tested this with https://github.com/fractal-analytics-platform/fractal-demos/commit/354fd7a9e33c296cc1ad050bcb03a700dfa1b824 and it's working now. Thanks a lot @tcompa !

I also opened a backlog issue so that we have a record of the edge-case issue coming up with edge detection, see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/255
