### ISSUE TITLE
Each attribute in `metadata` needs to exist somewhere else in the OME-Zarr file

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#212]
This would be the best-case scenario. Let's see whether we can enforce it strictly.

**Comment by jluethi** [comment]
Result from some conversation with people using OME-Zarrs:
1. We should **not** be using the OME-XML transitionary metadata. It's not meant for long-term and we don't need to get into that
2. We should be able to store arbitrary key-value pairs with metadata in the .zattrs. Let's think about where in the .zattrs they should go for each case and, if it's something more general, let's try to contribute it back to the spec

**Comment by jluethi** [comment]
> Are we currently using any of those? (or: is there an easily-accessible list?)

No, we aren't using it. It would have been one of the options to store additional metadata, see details here: https://ngff.openmicroscopy.org/latest/#bf2raw

I'm glad we don't need to get into this :)

**Comment by tcompa** [comment]
Current items that are in `metadata` and that we could think about moving to `.zattrs`:
1. Lists of plates/wells/images. These are already present in the `.zattrs` files, but it is convenient to duplicate them in the metadata to avoid a lot of parsing and string styling here and there.
2. Number of pyramid levels. This is also already available in the `.zattrs` files, if we accept that tasks should start by reading this information.
3. Coarsening factor. This is not directly available, but it can be retrieved with a bit of work from the `scale` transformations.
4. Channel list. This currently has an (ordered!) list like `["A01_C01", ...]`. Related to #211.

Then there are a few attributes which we use to smoothly propagate some parameters within pairs of associated tasks (server-side ref https://github.com/fractal-analytics-platform/fractal-server/issues/6). This is related to #177, that is, the choice of how to split arguments into two sets: the ones to be filled in automatically by fractal (e.g. `component` will most likely be here) and the ones to be specified as part of `args`.

Currently, we use
5. `original_paths`, to pass the image folders from zarr-creation task to `yokogawa_to_zarr`
6. `replicate_zarr` attributes (again, there are some paths of the original file to replicate), which are then used for the MIP task. This one we could in principle refactor, since it is probably a bit redundant.

Unless I've missed something, this is the current list.
Note that some of these parameters already exist in two forms, for (non-)multiplexing cases.

**Comment by tcompa** [comment]
Broadly speaking, I think that adding some key-value pairs to some `.zattrs` could be extremely helpful, e.g., for #211 (and maybe somehow also for #199 or #200).

**Comment by tcompa** [comment]
Note that once PR #239 is merge we won't have `channel_list` in `metadata` any more.

**Comment by tcompa** [comment]
Yesterday we re-discussed this issue, and we identified multiple (current) uses of `metadata`. Most of them should be deprecated, in favor of more specific sources of information.

1. Provide read/write access to component list ("read" from fractal-server, "write" from a combination of tasks and fractal-server). We plan to defer this functionality to a new task (ref #521). TBD later if this has to be a standard task or the "init" phase of a new, more complex, task object.
2. Store dataset information (e.g. `coarsening_xy` and the number of pyramid levels). This use is now deferred to #351; and then this use should be deprecated, and these parameters should not belong to `Dataset.meta`.
4. Store the dataset history -> this should not pass through `meta` any more - ref https://github.com/fractal-analytics-platform/fractal-server/issues/838.
3. Exchange information in a pair of tasks - ref #299. This is a way of using `meta` as a temporary buffer. 


Since each use of `metadata` is related to a specific issue, I'm closing this one.
