### ISSUE TITLE
Is cellpose actually running on the GPU?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#215]
Branching off from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/208

We get the following warning

`2022-11-21 14:05:53,341; INFO; TORCH CUDA version not installed/working.`

I think the model may actually not be running on the GPU. My understanding from cellpose instructions is that running torch on the GPU isn't set up with the default pip install cellpose, see here: https://github.com/MouseLand/cellpose#gpu-version-cuda-on-windows-or-linux

Let's discuss this here. Any ideas how to check whether it actually runs on the GPU? We could run models at high res (e.g. pyramid level 0 or 1 of a 3D image) on both the GPU node and the 16 core CPU node. The GPU node is supposed to be much faster.

I'll try this briefly to see how big the difference is and whether manually installing the GPU Torch makes a difference.

**Comment by tcompa** [comment]
> [](https://github.com/MouseLand/cellpose#gpu-version-cuda-on-windows-or-linux)
> 
> Let's discuss this here. Any ideas how to check whether it actually runs on the GPU? We could run models at high res (e.g. pyramid level 0 or 1 of a 3D image) on both the GPU node and the 16 core CPU node. The GPU node is supposed to be much faster.

The task already has a `use_gpu=True/False` variable, which is set by cellpose itself (via pytorch) and is the right place to look into. Unfortunately it is not printed as part of the current logs, but you can easily add it if you have access to the python file.

**Comment by tcompa** [comment]
Other than that, the standard way is to log in on the computing node (while the task is running), via
```
srun --jobid=$JOB_ID --pty /bin/bash
```
and use `nvidia-smi`. I've done it several times in the past, while developing the cellpose task, and it shows that some process is running on the GPU.

**Comment by jluethi** [comment]
Hmm, in the running workflow, I actually get this message then with the 2.1.1 cellpose version:
`/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.2/venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1190: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return forward_call(*input, **kwargs)`

And looking at `nvidia-smi`, nothing runs on the GPU. But I guess with a driver issue, that does make sense.
![Screenshot 2022-11-21 at 16 42 03](https://user-images.githubusercontent.com/18033446/203100226-1c2c5dcb-5dde-4177-a0a0-6872a1fac2e5.png)

**Comment by tcompa** [comment]
The first test I ran is example 05 (part of #218), where we just call `cellpose_segmentation` from a python script which is then run via SLURM. All looks fine in this case, with `use_gpu=True` in the logs and the `nvidia-smi` output below. Time-wise, segmenting a `(2, 2160, 2560)` array took ~100 seconds, which seems unlikely if we were running on CPU.
```
Tue Nov 22 07:53:23 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   41C    P0    27W /  70W |   3646MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     29943      C   python                                      3635MiB |
+-----------------------------------------------------------------------------+
```
Also the logs look good:
```
2022-11-22 07:52:19,397; INFO; ** TORCH CUDA version installed and working. **
2022-11-22 07:52:19,398; INFO; >> nuclei << model set to be used
```

**Important**: I installed `fractal-tasks-core` via poetry from the repository folder. I shall now try again with a `pip install`.

**Comment by tcompa** [comment]
I confirm that installing `fractal-tasks-core=0.4.3` from pypi leads to
```
2022-11-22 08:06:39,340; INFO; TORCH CUDA version not installed/working.
2022-11-22 08:06:39,340; INFO; >>>> using CPU
```

**Comment by tcompa** [comment]
Torch 1.13 deprecated old CUDA drivers, see release notes [here](https://pytorch.org/blog/PyTorch-1.13-release/#introduction-of-cuda-116-and-117-and-deprecation-of-cuda-102-and-113). And we are currently on CUDA 10.2, at UZH.

Poetry installs the version which is stored in the lock file, which is 1.12.1.
Pip installs the latest possible, which is 1.13.1. This is why it then fails in running on the GPU.

Current solution: we pin `fractal-tasks-core` to torch 1.12.1.
Long-term solution: we use a more recent CUDA (note that it may interfere with other software, like TissueMaps).

**Comment by tcompa** [comment]
> Current solution: we pin `fractal-tasks-core` to torch 1.12.1.

This is done, in #218.
I will release 0.4.4, and then re-run the test.

**Comment by tcompa** [comment]
Test with `fractal-tasks-core=0.4.5` correctly uses the gpu. This enables the GPU usage for cellpose at UZH.
Let's discuss updates for our dependencies or for CUDA somewhere else (since it also depends on the FMI setup).

**Comment by jluethi** [comment]
Thanks for figuring this out and the great summary!

On the Pelkmans lab side, we don't use GPUs via TissueMaps, just for some interactive uses on the cluster (e.g. running cellpose "manually"). But good solution for the moment to support the old CUDA version.
