### ISSUE TITLE
How are multiplexing cycle folders sorted?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#221]
At the moment we are sorting the cycle folders by name, which cannot be the right choice.
I guess we should simply use the order of the dataset resources.

**Comment by jluethi** [comment]
Order of resources is a good default for how we parse them into the OME-Zarr. Afterwards, they are ordered in the OME-Zarr based on the acquisition number.

We can eventually consider whether users should be able to e.g. reorder their resources or assign the order manually, but as long as there is one reproducible way to order them with the resource order, that should cover it for the time being.

**Comment by tcompa** [comment]
Fixed in 0.4.6 (https://fractal-tasks-core.readthedocs.io/en/stable/changelog.html).

**Comment by jluethi** [comment]
Can confirm, the reversed_cycles run of example 2 (https://github.com/fractal-analytics-platform/fractal-demos/tree/main/examples-v1/02_cardio_multiplexing) now is processed correctly and the 3rd cycle is presented as cycle 1 and loaded when the plate is loaded.
<img width="1803" alt="Screenshot 2022-11-24 at 17 18 47" src="https://user-images.githubusercontent.com/18033446/203829435-c0484584-f304-409d-813b-4cc39c1fa5bb.png">
