### ISSUE TITLE
Parsing error when > 99 Z planes in yokogawa_to_ome_zarr

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#236]
We've tested some larger datasets at the FMI today and noticed a parsing error. The dataset had 117 z planes. We correctly get an OME-Zarr file with 117 z planes, but the assignment of image files to Z planes has a reproducible bug. 

The Z planes are ordered by the way the sorting in the filesystem (/ sorting by filename) works. Thus, we start with 1-9, then 100 - 109, then 10, then 110 - 117, then 11 - end. That's obviously not the order we want to parse the images into the Z stacks. I think the issue arises because the filenames only have 1 leading 0 for double digit numbers and aren't made optimally for 3D images with >99 files. Nevertheless, we should handle this correctly based on the Z indices.

This means: Parsing Z by sorting filenames fails here, we'd need to sort by the integer of the Z plane.

Here's an image showing the wrong ordering when looking at a yz view (it's not that those bars are black, they are just close to background. But closer inspection confirms that they are slices 100- 117):

![Screenshot 2022-11-29 at 13 36 33](https://user-images.githubusercontent.com/18033446/204544747-ca1e16c0-ef56-429c-a89d-463880f38c16.png)

Here are some example filenames (as "ordered" when they are sorted by the filesystem, same mistake as Fractal currently makes):
![Screenshot 2022-11-29 at 14 46 31](https://user-images.githubusercontent.com/18033446/204564138-00739379-7f31-4288-8f1a-ea8f2ccf9a6a.png)

**Comment by tcompa** [comment]
Please re-test with `0.5.1`. In principle it should be fixed.

**Comment by jluethi** [comment]
Awesome, will run a test later today! Thanks for the super fast fix!

**Comment by jluethi** [comment]
I ran a test on this now. Everything is parsed correctly now in v0.5.1 :)

<img width="1803" alt="Screenshot 2022-12-01 at 11 17 21" src="https://user-images.githubusercontent.com/18033446/205027333-966d03fe-abb6-4991-aeb4-18568f7fd452.png">

I also added the example for this to the demos repo here: https://github.com/fractal-analytics-platform/fractal-demos/commit/c5ac24dc63021f6778980dce9ff656e899fcad44
And the small subset (runs in under a minute) is part of the test datasets here now: https://github.com/fractal-analytics-platform/fractal/issues/213#issuecomment-1333551782
