### ISSUE TITLE
Submodule and installation extra for tools?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#260]
We now have a `lib_metadata_checks.py` file which is not part of the tasks, but it's rather meant as an auxiliary tool (e.g. to be used as part of a notebook that allows a user to cleanup metadata and prepare a csv file - or at least this is my understanding). This file also imports matplotlib.

I propose that:
- [x] We move all files which are not part of the tasks to a subfolder called `tools` (or a similar name), so that they can be imported as `from fractal_tasks_core.tools.some_file import some_function`. This makes it a bit more clear that those files are never used as part of tasks that run within Fractal.
- [x] We add an "extra" section to pypoetry, where we collect those optional dependencies that are only required for the `tools`  submodule. In the end, one would install it like `pip install fractal-tasks-core[tools]` (if needed). This way we don't have to install packages like matplotlib on the SLURM cluster.

All of this is not critical at the moment, since we only have _one_ tool file and by the way we already indirectly depend on matplotlib somewhere else (although hopefully we can get rid of it in the future), but if the `tools` submodule grows it would be useful to keep it a bit isolated from the tasks (both in terms of files and dependencies).

**Comment by tcompa** [comment]
You can git-clone the repo, cd to that folder, and then `pip install .[tools]`.
Would that work?

**Comment by jluethi** [comment]
That sounds like a good solution, wasn't aware that this is possible.
I'll try that, thanks! :)
