### ISSUE TITLE
Handle more general unintended overlap from Yokogawa metadata

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#264]
We currently have the `remove_FOV_overlaps` function, which was intended to handle regular overlap. This mostly solves issues as https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/107 where there is a rounding error around 0.

I now started processing some of Koen & Maurice's HCA datasets, which were acquired with a 20x objective last year. In that metadata, we find much more overlap (not just around 0, but between most FOVs). See here for a FOV in an example wells (colored if they overlap).
![Screenshot 2022-12-12 at 16 17 42](https://user-images.githubusercontent.com/18033446/207085702-894832ab-44a9-4a92-8ae7-d560f9142675.png)

The overlap is typically a single pixel.

The `remove_FOV_overlaps` function seems to work for many wells, but fails in some, e.g. here it reliably fails in well `J22`.
![Screenshot 2022-12-12 at 16 18 24](https://user-images.githubusercontent.com/18033446/207086163-ca6d0113-bbb5-4195-bf2f-d99009f8b539.png)

```
2022-12-12 16:32:20,414; INFO; removing FOV overlaps for well='J22'
2022-12-12 16:32:20,417; INFO; iteration=1, removing overlap between fov_id_1=4 and fov_id_2=2
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 df_noOveralp = remove_FOV_overlaps(site_metadata)

File ~/Dropbox/Joel/FMI/Code/metadata_parsing/fractal-tasks-core/fractal_tasks_core/lib_remove_FOV_overlaps.py:202, in remove_FOV_overlaps(df)
    200 is_y_equal = abs(ymin_1 - ymin_2) < tol and (ymax_1 - ymax_2) < tol
    201 if is_x_equal + is_y_equal != 1:
--> 202     raise Exception(
    203         "Two overlapping FOVs MUST share either a "
    204         "vertical boundary or an horizontal one, but "
    205         f"{is_x_equal=} and {is_y_equal=}"
    206     )
    208 # Compute and apply shift (either along x or y)
    209 if is_y_equal:

Exception: Two overlapping FOVs MUST share either a vertical boundary or an horizontal one, but is_x_equal=False and is_y_equal=False
```

Apparently, FOV 2 & 4 overlap at the corner & the overlap function is not written in a way to handle this. Can we make the `remove_FOV_overlaps` function a bit more general to handle this case? I briefly looked into it, but couldn't figure out a good way for it

**Comment by tcompa** [comment]
Now available in 0.6.5
