### ISSUE TITLE
Default to finite tolerance in `check_well_for_FOV_overlap`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#270]

**Comment by jluethi** [comment]
Let's also change the default tolerances in run_overlap_check / check_well_for_FOV_overlap function from 0 to tol=e-10. 0 is not a good default to have, as it detects overlap that is just a rounding issue

**Comment by tcompa** [comment]
Closing in favor of https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/266
