### ISSUE TITLE
Example 02 fails at `Maximum Intensity Projection` => dask/zarr related?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#283]
I've tried example 02 with fractal-tasks-core 0.7.0 again. It passes the `Convert Yokogawa to OME-Zarr` task, but fails at `Maximum Intensity Projection` task. Currently, I'm getting a `JobExecutionError` there. I suspect this could also be related to the Zarr & dask updates like https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/280. Will get easier to see once we have a fix for https://github.com/fractal-analytics-platform/fractal-server/issues/451.

I'll run it with the process runner next so we find the actual Traceback here.

**Comment by tcompa** [comment]
Side comment:
[test_MIP](https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/tests/test_workflows.py#L150) uses the zarr from zenodo, which may be the reason of why this error does not appear in the CI.

To check.

**Comment by jluethi** [comment]
> [test_MIP](https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/tests/test_workflows.py#L150) uses the zarr from zenodo, which may be the reason of why this error does not appear in the CI. 

Great to know!

I couldn't reproduce it with the process runner now, which is quite confusing tbh. I'll rerun it with the slurm runner again to see if there are any more details there and will provide a minimal example to reproduce this

**Comment by tcompa** [comment]
> Side comment: [test_MIP](https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/tests/test_workflows.py#L150) uses the zarr from zenodo, which may be the reason of why this error does not appear in the CI.
> 
> To check.

I introduced a new test in https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/284/files, which does not use the zarr array from zenodo, but rather builds it in the standard way (create zarr, convert to zarr, copy zarr, mip).
This test goes through, at the moment, which means the error should be more subtle.

**Comment by jluethi** [comment]
Hmm, ok. Must be something more nuanced somehow. I updated example 02 here to be the minimal reproducing example: https://github.com/fractal-analytics-platform/fractal-demos/tree/03809c7f209ac8fb10da8b5d2199bed923006bfd/examples/02_cardio_small

When running it via slurm runner, I get the following JobExecutionError:

```
(fractal-client-1.0.0rc1) jluethi@pelkmanslab-slurm-master-001:~/v1_fractal/fractal-demos/examples/02_cardio_small$ fractal job show 1
{
  "project_id": 1,
  "input_dataset_id": 1,
  "output_dataset_id": 2,
  "workflow_id": 1,
  "overwrite_input": false,
  "worker_init": "export CELLPOSE_LOCAL_MODELS_PATH=/data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH\nexport NUMBA_CACHE_DIR=/data/homes/jluethi/.cache/NUMBA_CACHE_DIR\nexport NAPARI_CONFIG=/data/homes/jluethi/.cache/NAPARI_CACHE_DIR\nexport XDG_CONFIG_HOME=/data/homes/jluethi/.cache/XDG\n",
  "working_dir": "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001",
  "id": 1,
  "start_timestamp": "2023-01-18 11:16:05.385741",
  "status": "failed",
  "history": [
    "Create OME-Zarr structure",
    "Convert Yokogawa to OME-Zarr: ['20200812-CardiomyocyteDifferentiation14-Cycle1.zarr/B/03/0/']",
    "Copy OME-Zarr structure"
  ]
}

This is the job log:

JOB ERROR:
TRACEBACK:
JobExecutionError

COMMAND:
Content of /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.submit.sbatch:
#!/bin/sh
#SBATCH --output=/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.%j.out
#SBATCH --error=/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.%j.err
#SBATCH --partition=main
#SBATCH --mem=15g
#SBATCH --cpus-per-task=4
#SBATCH --job-name Copy_OME-Zarr_structure
export SRUN_CPUS_PER_TASK=4
export CELLPOSE_LOCAL_MODELS_PATH=/data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH
export NUMBA_CACHE_DIR=/data/homes/jluethi/.cache/NUMBA_CACHE_DIR
export NAPARI_CONFIG=/data/homes/jluethi/.cache/NAPARI_CACHE_DIR
export XDG_CONFIG_HOME=/data/homes/jluethi/.cache/XDG

export CFUT_DIR=/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001
srun /data/homes/fractal/.conda/envs/fractal-server-1.0.0rc1/bin/python -m fractal_server.app.runner._slurm.remote /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/cfut.in.zMpSATnLejPoi4GeDzY8qzor5zD78d4G.pickle
chmod 777 /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/*

STDOUT:
File /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.9447080.out is empty


STDERR:
Content of /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.9447080.err:
chmod: changing permissions of '/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/0.slurm.submit.sbatch': Operation not permitted
chmod: changing permissions of '/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/1_par_20200812-CardiomyocyteDifferentiation14-Cycle1_zarr_B_03_0_.slurm.submit.sbatch': Operation not permitted
chmod: changing permissions of '/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/2.slurm.submit.sbatch': Operation not permitted
chmod: changing permissions of '/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/cfut.in.zMpSATnLejPoi4GeDzY8qzor5zD78d4G.pickle': Operation not permitted
chmod: changing permissions of '/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/artifacts/workflow_000001_job_000001/workflow.log': Operation not permitted
```

When running it via the process runner on the cluster (as the fractal user), I get the MIP task to pass:
(was still a longer workflow, I kept it running after that task)
<img width="1116" alt="Bildschirm­foto 2023-01-18 um 12 10 42" src="https://user-images.githubusercontent.com/18033446/213158888-b87ce541-7e6b-423e-aae1-b27abb485808.png">

**Comment by tcompa** [comment]
Thanks for this info. My guess is that this is purely due to https://github.com/fractal-analytics-platform/fractal-server/issues/451, rather than an actual task error.

**Comment by jluethi** [comment]
> Thanks for this info. My guess is that this is purely due to https://github.com/fractal-analytics-platform/fractal-server/issues/451, rather than an actual task error.

That's possible, but all tasks have those errors. I then don't understand why it's triggering a JobExecutionError here...
To make future debugging of this easier: Wo we want to have the tracebacks in the task error log in any case, but just add some info about whether it appears to have been a JobExecutionError if we think there was one? Or at least have a debugging option for that, i.e. at higher verbosity or so. Because would be easiest to know see whether there is any traceback in the task if this can be exposed somehow.

**Comment by jluethi** [comment]
To make this search even more confusing: 
I generated a different test dataset that contains both the 01 and 02 example data in separate wells (for some tests with the napari plugin & differing well sizes). In that example, the processing on Fractal runs through successfully for both wells. Even though the data for that is exactly the same as the one in the example 02 which fails here.
As a sanity check, I then ran the exact script that worked for my new example on the old input data and there it fails again.

Thus: This example 02 only appears to fail if it only runs on a single well and only if it runs on the cluster. Somehow it then generates a JobExecutionError. But in other cases (running via process runner or running this exact dataset as part of a larger workflow), it does not trigger this error.

**Comment by jluethi** [comment]
Let's address https://github.com/fractal-analytics-platform/fractal-server/issues/451 first thus. Because maybe this will literally be solved through it (though I don't understand how it's currently getting triggered here and not for other examples).

**Comment by tcompa** [comment]
> Let's address [fractal-analytics-platform/fractal-server#451](https://github.com/fractal-analytics-platform/fractal-server/issues/451) first thus. Because maybe this will literally be solved through it

Yes, this is the most likely situation -- see https://github.com/fractal-analytics-platform/fractal-server/issues/451#issuecomment-1396689997.

**Comment by tcompa** [comment]
The workflow ran through, on the UZH cluster, after some fractal-server updates, see details at https://github.com/fractal-analytics-platform/fractal-server/issues/451#issuecomment-1396933093.

Closing now, let's re-open only for task errors, and otherwise let's report new findings of this kind on the fractal-server issues (existing or new ones).
