### ISSUE TITLE
Can we make the imagecodecs dependency optional?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#289]
After the issues with pyqt5 pip installation (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/286), there is another library that makes local installation tricky: `imagecodecs`

It fails the following way:
```
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      imagecodecs/_aec.c:756:10: fatal error: 'libaec.h' file not found
      #include "libaec.h"
               ^~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> imagecodecs

```

It installs fine via conda, but I tested a lot of workarounds for the pip installation (like trying to install some other packages via brew) and none of them work.

----

Why do we have the imagecodecs dependency? I think it's just to read the non-standard TIFF compression used at the FMI. If that's the only reason: Can we make it an optional dependency, i.e. one can `pip install fracta-tasks-core[imagecodecs]`? This TIFF compression will likely need to be supported at FMI for a while, though not sure how long depending on how workflows will develop in Fractal.

Or are there other reasons for the `imagecodecs` dependency?

**Comment by jluethi** [comment]
For context: We never import imagecodecs in the Fractal code itself

**Comment by tcompa** [comment]
In `fractal-tasks-core`, it is only required as [a cellpose dependency](https://github.com/MouseLand/cellpose/blob/main/setup.py):
```
$ poetry show imagecodecs
 name         : imagecodecs                                                 
 version      : 2023.1.23                                                   
 description  : Image transformation, compression, and decompression codecs 

dependencies
 - numpy *

required by
 - cellpose *
```

**Comment by jluethi** [comment]
Ah, that's too bad. Makes the optional idea much harder 🙈

**Comment by tcompa** [comment]
FYI:
* https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/248

**Comment by jluethi** [comment]
Hmm... Ok, I'll try to reproduce my workflow that seemed to work to avoid the imagecodecs issue. Not sure why it's coming up again.

**Comment by jluethi** [comment]
Ah, now I understand. Given our current setup, one can set up a local conda environment with fractal-tasks-core on Mac by doing the following:

```
conda create --name fractal-local-tasks python=3.9
conda activate fractal-local-tasks
conda install imagecodecs
pip install fractal-tasks-core==0.7.1a0
```
(specific version should not be required anymore after we test & release the dropping of qt dependencies)

And it's great that such manual local installation on Mac's is now possible.

Unfortunately, that only works because `imagecodecs` is installed from conda, which handles these potentially missing binaries depending on the architecture. Direct pip installation fails, thus the automated task collection still fails on Macs.

Given that this is a `cellpose` dependency, things do get a bit tricky here. Basically, `pip install cellpose` does not work on Mac with Apple Silicon chips at the moment.
The solution there currently is to use conda, which isn't something we can easily do in our current task collection.

Let's briefly discuss this at the call tomorrow.

**Comment by jluethi** [comment]
We won't be able to make `imagecodecs` dependency optional. But with our new workaround to install tasks manually on Macs & then register them to Fractal one-by-one with the new `fractal task new` client functionality, we have a workaround that avoids us having to tackle this problem.
See here for details: https://github.com/fractal-analytics-platform/fractal-server/issues/471
