### ISSUE TITLE
"no parent found" warning when loading labels through napari-ome-zarr

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#293]
After running the new `examples/05_cardio_tiny_dataset_cellpose/run_example_cellpose.py` (updated with #292), and opening the output with napari, we get a warning about label parents:
```
$ napari --plugin napari-ome-zarr tmp_out/20200812-CardiomyocyteDifferentiation14-Cycle1.zarr/B/03/0/

Assistant skips harvesting pyclesperanto as it's not installed.
14:51:25 WARNING no parent found for <ome_zarr.reader.Label object at 0x7f097b0d13f0>: None
```

This is printed by the `Label` class of the [ome-zarr-py reader](https://github.com/ome/ome-zarr-py/blob/master/ome_zarr/reader.py).

I'm not sure of whether this has always been there, but I only noticed it now.

**Comment by jluethi** [comment]
I think this has always been there, or at leas tbeen there for a while. I've seen this a few times already.

Not sure what it actually means though, I have never looked into it

**Comment by tcompa** [comment]
Note: we do create the `image-label` dictionary for labels, but we only fill it with `{"version": "0.4"}`, as per
> The `image-label` dictionary SHOULD contain a version key whose value MUST be a string specifying the version of the image-label specification.

**Comment by jluethi** [comment]
Ah, interesting. That would be good metadata to add to keep a record of what image the label image is based on. We're not currently using this anywhere. But good to eventually include.

The thing that will get potentially a bit complicated is that a label image can be created from multiple images (e.g. in a napari workflow)
