### ISSUE TITLE
Test data for organoid/nuclear labeling

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#298]
Would it be easy to prepare a testing dataset (with metadata) where one would first segment the organoids and then the nuclei inside each organoid? A few images (say around 4) would be enough.

This would be useful while working on #194, #195 and #45.

**Comment by jluethi** [comment]
Good point, I'll look into this. 

The Search First 1 dataset here could be useful: https://github.com/fractal-analytics-platform/fractal/issues/213 

Initial processing takes a bit, because there are many z planes. But one an MIP is made, it's just 14 FOVs or so.
With the current optimized settings for organoid segmentation with a custom network, no overlapping bounding boxes would be created. But I think I can tune the segmentation parameters so that some organoids are split up, thus appear in each others bounding box.

And then we can have an initial workflow to run once to generate the MIPs and easy testing on running different cellpose versions on that afterwards :)

**Comment by jluethi** [comment]
It looks like this:

![Screenshot 2023-02-15 at 16 46 18](https://user-images.githubusercontent.com/18033446/219078019-dd63e6ea-d520-421f-8134-060792c5ac22.png)

**Comment by tcompa** [comment]
I'm currently working with the aforementioned search-first dataset (see #194), so that there is no urgent need for another test dataset.

> But I think I can tune the segmentation parameters so that some organoids are split up, thus appear in each others bounding box.

This would be indeed useful.

**Comment by jluethi** [comment]
@tcompa I'm still exploring the parameters a bit. But for testing:
These parameters create some overlapping organoid segmentations. They are not good organoid segmentations, but the two small organoids in the middle left now would have overlapping bounding boxes:

```
{
    "wavelength_id": "A01_C01",
    "level": 2,
    "ROI_table_name": "well_ROI_table",
    "diameter_level0": 400,
    "cellprob_threshold": -3.0,
    "flow_threshold": 0.4,
    "output_label_name": "organoids"
}
```
(=> no more custom model & smaller diameter. I did not add the bounding box saving, as that would trigger an error in tasks 0.7.2 with the overlap)

**Comment by tcompa** [comment]
Thanks.

Side question: is there some advice on how to get "decent" nuclear segmentation for this dataset? Should I use again the custom Hummingbird model, or rather go with the cellpose default `nuclei`?

**Comment by jluethi** [comment]
I'll also test some parameters for nuclear segmentation on this dataset. I'll start with something like this:

```
{
    "level": 3, 
    "wavelength_id": "A01_C01", 
    "output_label_name": "nuclei", 
    "ROI_table_name": "well_ROI_table"
}
```

Hummingbird is optimized for finding large organoids, so will be fairly bad at finding nuclei. The default nuclei model may be decent. Could be that we need to tweak the diameter parameter. I'll try it out :)

The "organoid segmentation" achieved above was this:
![Screenshot 2023-02-20 at 10 30 54](https://user-images.githubusercontent.com/18033446/220069865-dbbef813-39ea-487a-9ec8-fc41a2d1a6f8.png)

**Comment by tcompa** [comment]
I could reproduce this sort of situation (image + organoid labels + nuclear labels), which is perfectly fine for testing of #194 and related issues:
![Screenshot from 2023-02-20 10-51-12](https://user-images.githubusercontent.com/3862206/220071709-ae5d7ea5-ab2b-4be6-b638-ad3c51a2418c.png)

**Comment by tcompa** [comment]
Parameters for the previous comment are as in
```python
# Cellpose for organoids
for component in metadata["image"]:
    cellpose_segmentation(
        input_paths=[zarr_path_mip],
        output_path=zarr_path_mip,
        metadata=metadata,
        component=component,
        wavelength_id="A01_C01",
        level=2,
        relabeling=True,
        diameter_level0=400.0,
        ROI_table_name="well_ROI_table",
        cellprob_threshold=-3.0,
        flow_threshold=0.4,
        pretrained_model="model/Hummingbird.331986",
        output_label_name="organoids_ROI_table",
        bounding_box_ROI_table_name="organoids_bbox_table",
    )

print("\n--------------------\n")

for component in metadata["image"]:
    cellpose_segmentation_bis(   # <--- THIS FUNCTION IS STILL IN PROGRESS
        input_paths=[zarr_path_mip],
        output_path=zarr_path_mip,
        metadata=metadata,
        component=component,
        wavelength_id="A01_C01",
        level=2,
        relabeling=True,
        diameter_level0=50.0,
        ROI_table_name="organoids_bbox_table",
        primary_label_ROI_table_name="organoids_ROI_table",
        output_label_name="nuclei_ROI_table",
        model_type="nuclei",
        flow_threshold=0.4,
    )
```

**Comment by tcompa** [comment]
This also means that we can close this issue, as far I am concerned. Testing data are available, and we found some parameters that lead to the relevant situation.

**Comment by jluethi** [comment]
Oh, that's nice! We should probably try something like `diameter_level0=20.0` for the nuclear segmentation to get more nuclei if we want this to be the realistic example (we're missing most nuclei at the moment). But for testing purposes, that looks great! :)

**Comment by tcompa** [comment]
> We should probably try something like diameter_level0=20.0 for the nuclear segmentation to get more nuclei if we want this to be the realistic example

See below, with both organoid and nuclear labeling acting at level=1.
In earlier tests I was working at level=3, and setting a small diameter lead to very few nuclei being identified.


![Screenshot from 2023-02-20 11-08-56](https://user-images.githubusercontent.com/3862206/220075824-558b225f-9e20-474a-a4df-fa2c50796d7e.png)

**Comment by jluethi** [comment]
That's great!

I'd say you can stay at the lower resolution for the organoids, thus creating overlaps in them.

And the nuclei can then be run at higher res & smaller diameter => some actual nuclei are found.

**Comment by jluethi** [comment]
We can also run the test completely like before of course. I'll prepare a little modified version of example 06 with these improved settings so we have a setup to demo the new functionality later :)

**Comment by jluethi** [comment]
I added a workflow example of this to the demo repo here: https://github.com/fractal-analytics-platform/fractal-demos/blob/ce34b2e42920d9848ad2fe4cb25b5c7f0f6aad5b/examples/06_search_first_custom_cellpose/run_example_overlapping_organoid.sh

![Screenshot 2023-02-20 at 17 19 28](https://user-images.githubusercontent.com/18033446/220157959-c628eba7-57fc-4d98-b224-c85efc83d60d.png)

Once we have the functionality integrated into the tasks, we can switch the ROI table for the nuclear segmentation and should be able to see whether it works (if the organoids actually overlap, the plugin only shows me the nuclear segmentation now)

side question: @tcompa how did you load multiple label images at once? The napari-ome-zarr plugin only ever loads the last label image, right?

**Comment by tcompa** [comment]
> side question: @tcompa how did you load multiple label images at once? The napari-ome-zarr plugin only ever loads the last label image, right?

The reader does load more than one image (https://github.com/ome/ome-zarr-py/blob/master/ome_zarr/reader.py#L191-L197), provided they are all listed in `labels/.zattrs`.
Our current cellpose task is wrong, since it has this block
```python
    labels_group = zarr.group(f"{zarrurl}labels")
    labels_group.attrs["labels"] = [output_label_name]
```
that simply replaces all existing labels with the current one. I'll open a reminder issue right now.
The upcoming task (as well as the napari-workflows one) do have the correct logic, which looks like:
```python
    new_labels = [output_label_name]
    try:
        with open(f"{zarrurl}labels/.zattrs", "r") as f_zattrs:
            existing_labels = json.load(f_zattrs)["labels"]
    except FileNotFoundError:
        existing_labels = []
    intersection = set(new_labels) & set(existing_labels)
    logger.info(f"{new_labels=}")
    logger.info(f"{existing_labels=}")
    if intersection:
        raise RuntimeError(
            f"Labels {intersection} already exist " "but are part of outputs"
        )
    labels_group = zarr.group(f"{zarrurl}labels")
    labels_group.attrs["labels"] = existing_labels + new_labels
```
