### ISSUE TITLE
How do task pairs share information?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#299]
Placeholder issue, branching from #177

> Concerning compound tasks: they are logical units of two tasks (a non-parallel preliminary task and a parallel execution) that need to share some data (possibly also parameters, but Dataset.metadata is a reasonable place for that). Note that the shared data are mostly a few paths, not the actual image data. The sharing can happen on-disk, possibly in a "temporary" location, or in the metadata inputs/outputs. Current preference is for using special key-value pairs in metadata dictionary, so that the workflow&task definition remains the same, and the compound-task would "only" exist as an additional endpoint.

**Comment by tcompa** [comment]
Ref:
* https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/300

**Comment by jluethi** [comment]
Revisit in the context of https://github.com/fractal-analytics-platform/fractal-server/issues/6, not urgent
