### ISSUE TITLE
Test full Fractal workflow on multi-well dataset

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#30]
Let's test the full workflow on a larger dataset, e.g. the 23 well plate. Let's not do any 3D segmentation or measurements here to keep this running somewhat fast.

**Comment by jluethi** [comment]
Conclusion from today's call: Let's make sure the current main of all 3 repositories can successfully run on some real data.
Once we have that and a "workflow script" for running this through the client, I can test the 23 well example.

**Comment by tcompa** [comment]
A basic example is ready (up to adding a few more tasks), see https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/1627e117238772f4bd036df4732615f4ebe2a96a.

**Comment by tcompa** [comment]
> Once we have that and a "workflow script" for running this through the client, I can test the 23 well example.

I'm not sure of why this issue is here (shouldn't it be part of `fractal`). Still, this example now exists in the `dev` branch of `fractal`, as of https://github.com/fractal-analytics-platform/fractal/pull/198.

Note that by now it was running on a local machine, while we should still play with https://github.com/fractal-analytics-platform/fractal-server/issues/4 before having a nice version working on SLURM.

**Comment by tcompa** [comment]
Examples are running both on the tiny dataset and on the 2x2-FOVs one, see https://github.com/fractal-analytics-platform/fractal-server/issues/4#issuecomment-1243407277. Both are single-well datasets.

I'm renaming this issue to be about multi-well examples.

**Comment by tcompa** [comment]
For the record, I ran the example in https://github.com/fractal-analytics-platform/fractal/blob/17127e0165070d620fbbdc4c1703fb8a48f39d74/examples/04_cardio_multiwell/define_and_apply_workflow.sh for a while, and it parses the 0-th level of a well in ~25 minutes.

Note that there are only 4 SLURM jobs running, but the number of wells is 10. And what is happening is that all 10 wells are being processed, at 4/10 of the maximum speed.

Refs: #91 and https://github.com/fractal-analytics-platform/fractal-server/issues/34

**Comment by jluethi** [comment]
> Note that there are only 4 SLURM jobs running, but the number of wells is 10. And what is happening is that all 10 wells are being processed, at 4/10 of the maximum speed.

Not sure I follow here. We submit 4 jobs max, but parsl actually runs all 10 workflows at the same time, 2-3 per slurm job?? I thought we currently run jobs using the whole node or have you already adapted that already? Eventually, for the parsing, many wells can probably run on the same node at full speed, because CPU & memory load shouldn't be that high.
Performance may scale sub-linearly depending on the IO speeds & the file system.

Or are the wells just being processes sequentially, i.e. only 4 at a time at the moment? Then the 4/10 speed makes sense to me.

**Comment by tcompa** [comment]
Building/writing pyramid level 1 is taking another 20-25 minutes, which seems too much when compared to level 0.

Did we introduce a performance regression with the new `build_pyramid` function? To be checked.

**Comment by tcompa** [comment]
For the record, parsing images and writing 5 pyramid levels to disk took ~50 minutes (with 4 SLURM jobs).

I have to stop this test now, but it's worth analyzing its behavior further.

**Comment by jluethi** [comment]
> Jobs are taking up entire nodes, indeed, but a slurm job does not match with a fractal task (parsl can send several tasks to a single slurm job). This is so, at the moment, because we are using parsl defaults. In legacy fractal, we forced one slurm job to correspond to one fractal task.

Hmm... Then maybe I've been thinking about the wrong thing when defining parsl executors. My reasonable specs were for how a Fractal task would run. If we pack multiple jobs in the same executor, then we can use larger slurm jobs. But we need some way to specify what a single task should take up or how many tasks run within a given node. Otherwise, we would have random out-of-memory errors if we can't control this.

> As long as we are on pelkmanslab, IO is very likely limiting.

Yes, that is to be expected for those tests. We also didn't record speeds for this dataset before, did we? Would be interesting to measure performance on the legacy branch, because it's well possible that we would have had a similar performance.

The 9x8 FOV, 23 well dataset took some 5-6 hours to parse, illumination correct & MIP while running 23 wells in parallel. So 20-50 min to process all wells through a task for 5x5 wells isn't crazy (maybe it's not fully optimized, but the performance not way off in my intuition).

Certainly worth testing more later! Not sure though whether this is a regression or just limiting IO :)

**Comment by tcompa** [comment]
> For the record, I ran the example in https://github.com/fractal-analytics-platform/fractal/blob/17127e0165070d620fbbdc4c1703fb8a48f39d74/examples/04_cardio_multiwell/define_and_apply_workflow.sh for a while, and it parses the 0-th level of a well in ~25 minutes.
> 
> Note that there are only 4 SLURM jobs running, but the number of wells is 10. And what is happening is that all 10 wells are being processed, at 4/10 of the maximum speed.
> [...]
> For the record, parsing images and writing 5 pyramid levels to disk took ~50 minutes (with 4 SLURM jobs).


For the record:

I'm playing with the parsl/slurm parameters, going in the direction of what we are discussing in this issue.
With the current (local) configuration, image-parsing for this example (10 5x5 wells) takes 17 minutes in total (instead of roughly 50 minutes). This is a bit reassuring, concerning the potential performance regressions I mentioned above.
The size of the output folder is ~100G.

Note that running this workflow only required few nodes the cluster:
* With `cpu-mid` parameters, one node with 64G memory can host four jobs (i.e. we only need 3 nodes to process the 10 wells of this example). Elapsed time in this case is ~17 minutes.
* With `cpu-low` parameters, one node with 64G memory can host all the ten jobs of this workflow (and more). I expect the elapsed time to be similar to 17 minutes (TODO: UPDATE THIS COMMENT WITH THE ACTUAL NUMBER).

Also for the record: the initial global task (`create_zarr_structure`) takes less than a minute.

**Comment by jluethi** [comment]
Sounds great, looking forward to testing this! :) The cpu configurations & corresponding logic hasn't been pushed to main yet, right? @tcompa Can you ping me when it has or when there is a stable dev branch where it would make sense for me to test? [no hurry! I have other stuff to get done as well :)]

**Comment by jluethi** [comment]
Sounds great, looking forward to testing this! :) The cpu configurations & corresponding logic hasn't been pushed to main yet, right? @tcompa Can you ping me when it has or when there is a stable dev branch where it would make sense for me to test? [no hurry! I have other stuff to get done as well :)]

**Comment by tcompa** [comment]
You can try the current config with
```
pip install fractal-client==0.2.1 fractal-tasks-core==0.1.5 git+https://github.com/fractal-analytics-platform/fractal-server.git
```

Notes:
* Several examples are available in the `examples` folder of the `fractal` repo (as available in the `main` branch).
* Some basic logs are available in the `server` folder, in `fractal.log`.
* The new parsl/slurm config was tested with basic parsing workflows, while I still need to check labeling tasks on gpus.

**Comment by jluethi** [comment]
Ok, I now reran these tests with fractal-server==0.1.4, fractal-client==0.2.1 fractal-tasks-core==0.1.6

In this way, the workflow on the 10 well, 5x5 dataset ran through successfully. Thus, I'd say we can close this issue & have completed the milestone :)

![Screenshot 2022-09-26 at 15 53 43](https://user-images.githubusercontent.com/18033446/192294512-42a2981a-0264-4f72-bbbc-99c1f4362120.png)
