### ISSUE TITLE
Refactor tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#300]
Branching from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/177, here is the plan for a sizeable refactor of tasks. This will be enough for fractal-tasks-core 0.8.0

- [x] Replace pathlib.Path arguments with strings in all task call signatures. Convert strings to Path objects inside the task, when this is useful.
- [x] In all `TaskArgument` models (the one that are then passed to the `run_fractal_task` function), remove defaults and mark optional arguments as `Optional`. Then, when actually calling the task function, use `**args.dict(exclude_none=True)` as arguments (instead of the current `**args.dict()`).
- [x] Due to previous point, do not check the mismatch between type hints in the function call signature and in the pydantic arguments model.
- [x] When we currently rely on an input_path structure like `/some/path/*.ext`, refactor the task call signature and introduce two separate arguments (`/some/path` and `*.ext`). This will (as part of a different issue) pave the way for more complex glob patterns (e.g. "I only need images from a given Z plane").
- [x] Related to the previous point: also add the glob_pattern to the metadata dict, so that downstream tasks can use it.
- [x] Update the manifest, to also have this argument.
- [ ] #324
- [x] Update tests.
- [x] Update (at least some of) the examples.
- [ ] Update (at least some of) the fractal-demos examples.

Something else?

**Comment by tcompa** [comment]
(updated as of https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/177#issuecomment-1432977235)

**Comment by tcompa** [comment]
> One thing I just realized though: Currently, to the user, the '.png' or '.tif' is not a task parameter, but something that is defined when adding a resource => the task can just read it from the resource? Or how does it go from the resource to the task? Does Fractal-server combine it with the base folder string and just provide that combination?

You're totally right, we did not consider this (I probably had some old versions of the tasks in mind).
This means that the such a change (moving away from the current "let's extract the extension from the path", towards two separate arguments) would have more consequences, also affecting what we define as a resource.

Let's re-discuss it.

**Comment by jluethi** [comment]
They are provided separately on resource adding, so could still be feasible to just pass them over as separate arguments instead of combining them. Let's discuss tomorrow :)

**Comment by tcompa** [comment]
>  In all TaskArgument models (the one that are then passed to the run_fractal_task function), remove defaults and mark optional arguments as Optional. Then, when actually calling the task function, use **args.dict(exclude_none=True) as arguments (instead of the current **args.dict()).

Concerning this one, for the record, let's observe that this script
```python
from pydantic import BaseModel
from typing import Optional


class Model(BaseModel):
    x: Optional[int]


m = Model()
print(m.dict(exclude_unset=True))
print(m.dict(exclude_unset=None))
print()

m = Model(x=None)
print(m.dict(exclude_unset=True))
print(m.dict(exclude_unset=None))
print()
```
produces this output:
```
{}
{'x': None}

{'x': None}
{'x': None}
```
and therefore the correct flag to use is `exclude_unset=True`.

**Comment by tcompa** [comment]
We'll split this issue into multiple parts, to make it easier to integrate other changes for this repo.

PR #303 (to be merged asap) takes care of
* Replace all `pathlib.Path` task arguments with `str` arguments, and update tests accordingly (tests are a bit cumbersome sometimes, in going back and forth between paths and strings, but the important point is that they do call the task functions with string arguments and then would fail if the task is not properly handling the argument).
* In all `TaskArgument` models (the one that are then passed to the run_fractal_task function), remove defaults and mark optional arguments as Optional. Then, when actually calling the task function, use `**args.dict(exclude_none=True)` as arguments (instead of the current `**args.dict())`.
*  Due to previous point, do not check the mismatch between type hints in the function call signature and in the pydantic arguments model.

**Comment by tcompa** [comment]
Related to
> When we currently rely on an input_path structure like /some/path/*.ext, refactor the task call signature and introduce two separate arguments (/some/path and *.ext). This will (as part of a different issue) pave the way for more complex glob patterns (e.g. "I only need images from a given Z plane").

and

> Related to the previous point: also add the glob_pattern to the metadata dict, so that downstream tasks can use it.

How should we call these two new arguments?
In #323 I'm provisionally using `image_extension` and `image_glob_pattern` (with the latter being only a placeholder in view of #301), but I'm open to better names.

**Comment by tcompa** [comment]
Out of scope for this issue (and for PR #323):
* #324, since it requires more thoughts.
* https://github.com/fractal-analytics-platform/fractal-demos/issues/29
