### ISSUE TITLE
Bug in `cellpose_segmentation` (or visualization)? Unexpected number of Z planes for labels

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#302]
As part of https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/194, I am setting up a fresh tasks-only example (see `examples/06_secondary_labeling` in the `194-store-masked-array-to-zarr` branch).
After performing MIP, and acting on the 2D data with the `cellpose_segmentation` task, the output labels have the wrong dimension (they should be 2D, but they still somehow include a non-trivial channel dimension). See shape attribute in the `.zarray` file:
```
$ cat tmp/RS220304172545_mip.zarr/A/06/0/0/.zarray 
{
    "chunks": [
        1,
        1,
        2160,
        2560
    ],
    "compressor": {
        "blocksize": 0,
        "clevel": 5,
        "cname": "lz4",
        "id": "blosc",
        "shuffle": 1
    },
    "dimension_separator": "/",
    "dtype": "<u2",
    "fill_value": 0,
    "filters": null,
    "order": "C",
    "shape": [
        4,
        1,
        10800,
        7680
    ],
    "zarr_format": 2
```

**Comment by jluethi** [comment]
Ah, I have seen that our MIPs in napari sometimes had 4 Z steps instead of 1, but could never figure out what it was there. That would explain things! And if it's that, this has been around for a while :)

Cellpose used to return multiple arrays (the masks, the flows, some diameters and, before we changed the model class, also some styles). Any chance we're assigning all cellpose outputs here to the output, not just the masks?

**Comment by tcompa** [comment]
Update: the problem seems to be with the MIP and not with the cellpose_segmentation task.
(this is clear by just looking at the .zarray file above.. no cellpose segmentation was performed yet, but the shape is wrong)

**Comment by tcompa** [comment]
Logging what I observe.

Even after playing a bit with cellpose_segmentation (I cannot say yet whether I found some bug), I observe something unexpected.
Now the label .zarray file looks fine (that is, a single Z plane in the shape):
```
$ cat tmp/RS220304172545_mip.zarr/A/06/0/labels/organoids/0/.zarray 
{
    "chunks": [
        1,
        1,
        1350,
        960
    ],
    "compressor": {
        "blocksize": 0,
        "clevel": 5,
        "cname": "lz4",
        "id": "blosc",
        "shuffle": 1
    },
    "dimension_separator": "/",
    "dtype": "<u4",
    "fill_value": 0,
    "filters": null,
    "order": "C",
    "shape": [
        1,
        1,
        1350,
        960
    ],
    "zarr_format": 2
```
The same is true for the image data (that is, a single Z plane in the shape):
```
$ cat tmp/RS220304172545_mip.zarr/A/06/0/0/.zarray 
{
    "chunks": [
        1,
        1,
        2160,
        2560
    ],
    "compressor": {
        "blocksize": 0,
        "clevel": 5,
        "cname": "lz4",
        "id": "blosc",
        "shuffle": 1
    },
    "dimension_separator": "/",
    "dtype": "<u2",
    "fill_value": 0,
    "filters": null,
    "order": "C",
    "shape": [
        4,
        1,
        10800,
        7680
    ],
    "zarr_format": 2
```

Now back to napari.

If I open the label images alone, with
```
poetry run napari --plugin napari-ome-zarr tmp/RS220304172545_mip.zarr/A/06/0/labels/organoids/
```
I only see one Z plane, as expected.

However if I open the whole image, with
```
$ poetry run napari --plugin napari-ome-zarr tmp/RS220304172545_mip.zarr/A/06/0/
```
I do observe that the labels span 4 Z planes.

What are these 4 Z planes?
One guess is that 4 is the number of channels, but why would we see the labels replicated four times?
Also: do we have something wrong in our output, or is it a bug in the napari visualization when combining a multi-channel 2D image with a single-channel 2D label?

**Comment by tcompa** [comment]
> Ah, I have seen that our MIPs in napari sometimes had 4 Z steps instead of 1, but could never figure out what it was there. 

Still to be understood whether this has to do with MIP.
If I just produce this MIP and open it in napari (at the plate, well or image level) I only see one Z plane. It's when I add cellpose labels that I see four Z planes (but for the labels only! the image data only populate the first Z plane).

**Comment by jluethi** [comment]
I also wasn't sure whether this is a napari bug or our bug, so I never reported it here.

As far as napari is concerned, it has 4 separate channels and then the label image, so I doubt this should be the issue, but who knows.

If we can validate that our OME-Zarr really only has 1 plane, then I'd guess visualization bug.
But before, you reported an OME-Zarr with a label image that had a shape of:

```
    "shape": [
        4,
        1,
        10800,
        7680
    ],
```

That looks like we're pretending our label image has 4 channels (or whatever the top dimension here would be)

**Comment by tcompa** [comment]
For the record:
* `napari --plugin napari-ome-zarr tmp/RS220304172545_mip.zarr` correctly shows the plate, with a single Z plane and no labels.
* `napari --plugin napari-ome-zarr tmp/RS220304172545_mip.zarr/A/06` correctly shows the well, with a single Z plane and no labels.
* `napari --plugin napari-ome-zarr tmp/RS220304172545_mip.zarr/A/06/0` has a "buggy" behavior.

The "buggy" behavior is really weird.
* Upon opening the image, napari says that there are 5 Z planes (from 0 to 4), and that the visualization starts from the first one (i.e. the 0/4 one). In this Z plane there are both image data and labels.
* Moving the slider to the second Z plane (i.e. the 1/4 one), there are no image data but there are labels.
* Moving the slider to the third Z plane (i.e. the 2/4 one), there are both image data and labels - which is very confusing.
* Going to the one-but-last and last planes there is no image data, but only labels.
* Going back to the first Z plane, now there are no data any more! Something is clearly wrong, since image data "moved" from plane 0/4 to plane 2/4 during visualization..

**Comment by jluethi** [comment]
This does not appear to be a Fractal issue, but rather something on the napari-ome-zarr side
