### ISSUE TITLE
Add coverage reports to fractal-tasks-core

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#321]
Would be nice to add the same test coverage reports to the fractal-tasks-core repo that we have on the server & client repo, both for PRs and the coverage info at the top of the README.

**Comment by tcompa** [comment]
Once [the current CI](https://github.com/fractal-analytics-platform/fractal-tasks-core/actions/runs/4292193637) is over, this is in principle ready. The report should then be available [here](https://htmlpreview.github.io/?https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/python-coverage-comment-action-data/htmlcov/index.html).

**Comment by jluethi** [comment]
Awesome, thanks!
