### ISSUE TITLE
Turn `input_paths` into zarr filenames?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#324]
Branching from #300

> For all tasks that take a zarr input, they currently need `input_paths` to be like `["/some/path/*.zarr"]` and `component` to be like `plate.zarr/B/03/0`. Refactor this so that `input_paths` is like `["/some/path/plate.zarr"]` and `component` is like `B/03/0`.

This issue is not yet fully defined.

**Comment by jluethi** [comment]
Including it in the input path makes sense.
Including it in the output path could get tricky, as the Zarr name is currently created by the first task => the server doesn't know the Zarr name string before running the first task.

Also, if we think about the user being able to specify it: Do they need to know the actual full string beforehand to specify what input will be used in e.g. task 6 of a workflow? The user may also not know yet.
Or can we refer to the Zarr file by a label (e.g. "original", "mip")?

Also, having multiple Zarr files may be transitionary, potentially things will all be in 1 Zarr file. In that mindset, it would make sense that it's all in the component, not the input?
