### ISSUE TITLE
`diameter_level0` was made a required parameter in current task dev => revert back to Optional?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#327]
`diameter_level0` was made a required parameter in the newest version of the cellpose task by not having an Optional flag anymore in the `TaskArguments`.

It's the most important hyper-parameter of running a cellpose model, so there is an argument to be made for this. But if we wanted to achieve that, we should remove our own defaults from the `cellpose_segmentation` and `segment_FOV` functions and actually use the model defaults. That would get tricky with optional required upscaling though.

And I would argue for reverting this back to Optional in general. I think it came in through one of my PRs now and the change of Optional parameter handling at the same time, so likely unintentional.

**Comment by tcompa** [comment]
You're right. It's because in https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/fe2866212480f66dfc981bec92cc8b57c6eea0c8 we removed the default from the pydantic model, and this automatically turned it into a required argument.
