### ISSUE TITLE
Add glob-pattern feature to `parse_yokogawa_metadata`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#332]
## Context

While working on https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/301, we realized that we also need a way to update the FOV/well ROI tables according to the given glob pattern. If not, the loop-over-ROIs in yokogawa_to_zarr will fail when there are no images left - see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/331.

## To do

- [x] In `parse_yokogawa_metadata`, take an additional argument `glob_patterns` - to be propagated to `read_mlf_file`.
- [x] In `read_mlf_file`, extract the filename column from the XML-parsed dataframe; then select only rows where this column matches `glob_patterns`, and ignore the others.
- [x] In `parse_yokogawa_metadata`, return a dictionary mapping `well_id` to `num_files_per_well`, where `num_file_per_well` is computed as `len(subframe)`, and where `subframe` is the dataframe corresponding to the `well_id` index. This return value should replace the current `total_files` one, which is not used anywhere (also: remove the corresponding TODO comment).
- [x] In `create_ome_zarr`, compare the number of files (per well) obtained via two approaches: (1) from `parse_yokogawa_metadata`, and (2) from the actual globbing of files. If the two numbers do not match, fail with a relevant error message.
- [x] The number-of-files hard check should only be performed for when the metadata are extracted via `parse_yokogawa_metadata`, while it should be skipped when a custom metadata dataframe is provided as a task input.
- [x] To check: update `create_ome_zarr_multiplexing` accordingly, unless we find something unexpected

**Comment by jluethi** [comment]
Great summary, thanks @tcompa !

**Comment by tcompa** [comment]
Side note: if the mlf file includes file names ending  with `.tif` but the images file names end with `.png`, this is not expected to work - unless we decide that we can ignore the filetype extension (in `read_mlf_file`) and only use the other patterns (if any).

**Comment by jluethi** [comment]
Ah, I didn't think about that! Can we exclude the filename extension from this check? This will regularly be the case for Pelkmans lab datasets. We tend to run PNG compression on all our images, but keep the rest of the filename the same.

For filtering the mlf file, we only have the image files in there anyway, so we don't need to filter for filename extensions.

**Comment by tcompa** [comment]
This is mostly ready in #326 (just missing the multiplex task update), but I'm left with a doubt about regular expressions.

As part of #326, we currently support globbing only image filenames that match some patterns. Valid examples include:
```python
pattern = "*something*"
pattern = "*something*else*"
pattern = "*F00[1-3]*"
pattern = "*.png"
pattern = "*something*else*.png"
```

The same patterns are used for regex-matching somewhere else in the code, where the `re` library is used under the hood - this happens through pandas [`Series.str.fullmatch` method](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.fullmatch.html).

The re syntax is not exactly the same as for glob, see [docs](https://docs.python.org/3/library/re.html#regular-expression-syntax). In glob, on the contrary, ["The pattern may contain simple shell-style wildcards a la fnmatch"](https://github.com/python/cpython/blob/3.11/Lib/glob.py#L17-L20) - see [fnmatch specs](https://docs.python.org/3/library/fnmatch.html).

For this reason, we need to take care of some specific cases:
* The `"*"` wildcard in glob should become `".*"` for re.
* The `"."` character in glob should be escaped (i.e. `"\."`) for re.
With these two, we would already cover the patterns listed above. By adding maybe another check for `"?"` we would cover quite a few cases. But I'm not totally happy of this "custom" conversion between different pattern syntaxes.

Possible ways out:
A. Check that the supported patterns already cover what we consider as intended usecases, and postpone working on a more elegant solution.
B. Write our own glob function which uses glob for a full list of files and then uses `re` for regex matching (and check that its performance is OK).

Opinions on this would be appreciated.

**Comment by tcompa** [comment]
> Opinions on this would be appreciated.

Problem solved (thanks @mfranzon), thanks to https://docs.python.org/3/library/fnmatch.html#fnmatch.translate
