### ISSUE TITLE
Write `region` key into ROI tables coming from labels

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#333]
As per https://github.com/ome/ngff/pull/64, the .zattrs file of a given label table:
```
# `.zattrs` MUST contain "type", which is set to `"ngff:region_table"`
# `.zattrs` MUST contain "region", which is the path to the data the table is annotating.
# "region" MUST be a single path (single region) or an array of paths (multiple regions).
# "region" paths MUST be objects with a key "path" and the path value MUST be a string.
# `.zattrs` MUST contain "region_key" if "region" is an array. "region_key" is the key in `obs` denoting which region a given row corresponds to.
# `.zattrs` MAY contain "instance_key", which is the key in `obs` that denotes which instance in "region" the row corresponds to. If "instance_key" is not provided, the values from the `obs` `.zattrs` "_index" key is used.
```
where for the moment we stick with `"region" MUST be a single path (single region)`, rather than `an array of paths (multiple regions).`

This is related to ongoing work on "secondary" labeling, cf #306 and refs therein

**Comment by jluethi** [comment]
Hey Tommaso,

The spec also isn't accepted yet and I'm not 100% convinced that some things wouldn't change (slightly) again, so I wasn't pushing for us to fully adopt it yet.

My best guess for it is this:
```
{
    "encoding-type": "anndata",  # As you had it
    "encoding-version": "0.1.0",   # As you had it
    "type": "ngff:region_table",    # As you had it. There is a discussion that there could be other tables as well, e.g. our FOV ROI tables don't fit this definition
    "region": {"path": "../labels/label_DAPI"},        # I'm not entirely sure how those paths are formatted. See below
    # "region_key":  "xxx",            # not needed, because we only use a single region => agreed
    "instance_key": "label"              # This should be the label column. I'd be hesitant to use the index column, even if we set it to the label values. What if we reindex for some reason? The label column should remain consistent
}
```

Regarding the paths: the relative path logic would work on filesystems. But I don't think that's how it works on cloud instances, so I'm not really sure how they are supposed to be formatted and also couldn't find that out yet.
I'll investigate this question a bit more and see if I can find example files in the thread.

**Comment by jluethi** [comment]
In some example discussion, this was given as an example:
```
{
    "region": ["segmentation_masks0", "segmentation_masks1"],
    "region_key": "which_segmentation",
    "instance_key": "label_value"
}
```

That would argue for the path to just be `label_DAPI`.

I'll reach out to some of the devs to try & get an answer :)

**Comment by tcompa** [comment]
> # This should be the label column. I'd be hesitant to use the index column, even if we set it to the label values. What if we reindex for some reason? The label column should remain consistent

To clarify something which is possibly confusing (also in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/334#issuecomment-1460631771): I totally agree with using the "label" column, and I'm not proposing to use the index. The "ROI_index" that you saw in #306 was just the positional index of which ROI we are analyzing, and it has nothing to do with the DataFrame index. The actual label value would then be something like: "take the {ROI_index}-th element from the label column".

It was a bad variable-name choice, I agree, but we are on the same page about using the label column and not the dataframe index.. Anyway, work on this #333 issue will also change that part.

**Comment by jluethi** [comment]
Sounds good :)

Let's stay consistent by naming all of our ROI tables something with "ROI" in the name. We don't enforce this for the users, but can do so in the examples :)
