### ISSUE TITLE
ROI-table origin

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#339]
Right now, we have two different kinds of ROI tables (stored as AnnData tables in the `/tables` subgroup):
* FOV/well ROI table are generated as in: mlf/mrf file --> pandas dataframe --> anndata table (or possibly directly from a pandas dataframe, if the user provides it)
* Bounding-box ROI tables for labelled objects are generated as in: run a segmentation (either via cellpose or napari-workflows) and produce a label array --> call our own `array_to_bounding_box_table` function to produce a pandas dataframe --> convert from pandas to anndata

For the first kind of ROIs, the origin (in physical units) is arbitrary. E.g. the well ROI could start at `(-501.4, 100, 33.3)` (in micrometers). When converting one such ROI to integer array indices, in `convert_ROI_table_to_indices`, we reset the origin to (0,0,0) by just taking the minimum values along the three directions:
```python
        origin_x = min(ROI[:, x_pos].X[:, 0])   # where x_pos="x_micrometer", for instance
        origin_y = min(ROI[:, y_pos].X[:, 0])
        origin_z = min(ROI[:, z_pos].X[:, 0])
```
This then produces indices which start (correctly) at (0,0,0).

For the second kind of ROIs, the origin is already set to (0,0,0) micrometers, and we don't have to do anything.

Issues with the current situation:
1. The origin-reset functionality only works if the ROIs in a table cover the whole well, while it totally fails if they are sparse (ref #304).
2. The required different way to convert a ROI table to a table of indices is unclear. When should we proceed in one way or another?

To do: let's check whether ome-ngff has attributes where we could store the origin value. If so, we could then also use it for our custom ROIs (e.g. the organoid bounding boxes), and we'll have a single homogeneous set of ROIs - all in the same reference frame. If ome-ngff doesn't offer a relevant feature, we should either add it ourselves or take the most conservative approach (i.e. all ROIs should have origin (0,0,0) by construction).

**Comment by tcompa** [comment]
As part of #306, we are now hard-coding the following heuristics:
```python
    # Heuristic to determine reset_origin #FIXME
    if ROI_table_name in ["FOV_ROI_table", "well_ROI_table"]:
        reset_origin = True
    else:
        reset_origin = False
    logger.info(f"{reset_origin=}")
```

This is clearly a provisional workaround, waiting for a more reliable solution.

**Comment by jluethi** [comment]
Thanks for opening the issue @tcompa !

> For the second kind of ROIs, the origin is already set to (0,0,0) micrometers, and we don't have to do anything.

This means that our derived ROIs aren't saved in the same "physical" space / transformation as the well / FOV ROIs, which could get confusing in other places down the road.

We should decide that either:
a) Everything is saved with (0, 0, 0) origins => limits flexibility of ROIs (especially when externals contribute them) and we loose potential information (e.g. if different multiplexing cycles have different origins, that may be relevant initialization information for a registration approach)
b) We save the origin for each well explicitly and have everything in that space: Requires figuring out where this origin is saved (=> I'll look into this), some additional calculations for the new ROI case and potentially an additional requirement to OME-Zarr files we'd process

I'd overall also favor approach b of having an explicit origin, but we should check whether we can make this requirement somewhat soft (to not be too strict with external OME-Zarr files)

**Comment by tcompa** [comment]
> to not be too strict with external OME-Zarr files

For the record, there is just no generally-valid way to use a ROI table from an externally-contributed ome-zarr file which has an implicit assumption on the origin (e.g. a non-zero origin).

I agree that we should try to avoid hard constraints on those files, but this probably becomes a question about which default behavior to choose when no origin information is specified -  for instance one in
* Always assume that the origin is at 0;
* Always reset the origin (this will break for sparse ROIs);
* ... ?

**Comment by jluethi** [comment]
We could go with: If there is an origin specified, always use this. And all our data will have an origin specified. If no origin is specified in the OME-Zarr, give a warning and assume the origin is (0, 0, 0).

But let's see first if we can use an origin reasonably :)

**Comment by jluethi** [comment]
This comes up again and makes issues in the following areas:
- Bugs related to different assumptions on ROIs: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/460
- Issues with using ROIs for registration: https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/487#issuecomment-1674896111
- Code complexity in e.g. the roi loader plugin, having to load FOV & well ROIs differently from other ROIs.

In all cases, I think it will be important to make sure that:
a) All ROIs are stored relative to the same origin
b) The lowest value in any of the ROIs isn't necessarily the origin (as we currently assume for the FOV/well ROIs)

I can see 2 routes:
1. We go with origins as 0, 0, 0
2. We store the actual origin spatial coordinate somewhere (as suggested above) and always calculate relative to that.

I am getting around to just have 0,0,0 origins meaning the top left of the image. Option 2 will add additional complexity whenever we want to load ROIs. 
The two reasonable way I could see non 0, 0, 0 origins is 
I) if there were specific origin zyx columns. 
II) If the OME-NGFF metadata contain

For I) with the `x_micrometer_original` & `y_micrometer_original` columns we have from the Yokogawa converter, we do already save this info. At the MD, we're anyway not currently storing any world coordiantes in the ROI tables, even the FOV & well ROI tables have a 0 origin.
For II) Then loading ROIs would get a bit more annoying, as one needs to load both the ROI table + that metadata (and what if one is missing?)

-----

Bigger picture: 
1. Do we need these world coordinates that related to original stage positions?
2. Do they need to be part of our ROI definition? Are ROIs relative to world coordinates?

Likely yes for 1 in some manner, but could be in some other metadata. Do ROIs ever need to be aware of the world coordinates (=> 2)? There are some potential scenarios, e.g. if during a multiplexing experiment, one images different FOVs and wants to get a rough alignment based on stage coordinates. But that's a very edge case, not sure how relevant that will be.

=> seems to me that we could go with 0, 0, 0 origins and treat those edge cases via specific metadata if necessary

**Comment by tcompa** [comment]
Here is the current situation (before #487), in non-registration-related tasks:

1. The yokogawa-based create-ome-zarr tasks (i.e. the ones in fractal-tasks-core) produce ROI tables for the FOVs and well; this ROIs have non-zero origin coordinates, as based on yokogawa metadata
2. The yokogawa-to-zarr task uses the FOV/well ROI tables, and it calls `convert_ROI_table_to_indices` without the `reset_origin` argument (that is, with the default `reset_origin=True`). This is consistent, since the resulting indices are then used to access regions of arrays, and then must obviously be in a `[0, num_pixels - 1]` interval
3. The illumination-correction task uses the FOV ROI table, again with `reset_origin=True` (the default parameter for `convert_ROI_table_to_indices`), for the same reason as in point 2
4. The copy-zarr task does not require the table->indices transformation
5. The MIP task acts in the same way as illumination-correction in point 3
6. The cellpose task loops over the ROIs listed in a user-provided table (defaulting to `input_ROI_table="FOV_ROI_table"`). When extracting indices from `input_ROI_table`, it uses this logic:
    ```python
    # Heuristic to determine reset_origin   # FIXME, see issue #339
    if input_ROI_table in ["FOV_ROI_table", "well_ROI_table"]:
        reset_origin = True
    else:
        reset_origin = False
    logger.info(f"{reset_origin=}")

    # Create list of indices for 3D ROIs spanning the entire Z direction
    list_indices = convert_ROI_table_to_indices(
        ROI_table,
        level=level,
        coarsening_xy=coarsening_xy,
        full_res_pxl_sizes_zyx=full_res_pxl_sizes_zyx,
        reset_origin=reset_origin,
    )
    ```
    This means that when it is run on some of the "standard" ROI tables (FOVs or well) it will first reset the origin (which makes sense, since they are defined with non-zero origin and then it wouldn't make sense to directly convert them to indices). In the other case (running e.g. with `input_ROI_table="organoid_bounding_boxes_ROI_table"`), we are assuming that the table is already defined in a suitable reference frame, and we do not want to alter this definition. Note: it may be tempting to always reset the origin, but this requires additional information which is sometimes not available (e.g. if `organoid_bounding_boxes_ROI_table` is a table which is sparse, and does not fully cover the area of its parent ROI - e.g. the well or FOV one).

8. The cellpose task also creates a ROI table for the label bounding boxes, which has zero-origin (note: this is bugged, when `input_ROI_table` has more than one entry: ref #460).
9. The napari-workflows task also has the `input_ROI_table` parameter (again defaulting to `FOV_ROI_table`), but we did not include the same logic as in cellpose. This is maybe because we were not planning to use this task for nuclear segmentation within organoid ROIs? Or maybe we just postponed implementation of this feature.

**Comment by tcompa** [comment]
Current #487 registration tasks:

9. `calculate_registration_image_based` acts in the same way as other tasks about the input ROI table: it calls `convert_indices_to_regions` (both for reference/actual cycles) with `reset_origin=True` (the default argument). It then writes back to the the (actual-cycle) ROI table, after including three new `translation_{x,y,z}` columns.
10. `apply_registration_to_ROI_tables` acts at the well level, and reads all relevant ROI tables from the different cycles into the `roi_tables` dictionary. For each ROI (i.e. for each cycle), it then resets the origin to zero. Then, for each (non-reference) cycle, the tasks actually applies registration to a new ROI table (e.g. `new_roi_table = "registered_" + roi_table`, if not provided as a task argument).
11. `apply_registration_to_image` calls the `convert_indices_to_regions` with `reset_origin=False`, to prepare the relevant array indices. As far as I understand, this is because the registration operation (in the previous task) leads to non-zero-origin ROI tables, and this information is crucial when comparing two cycles (that is, if we reset all origins then we wouldn't know what/where to write data in new arrays). @jluethi am I getting this right?

**Comment by jluethi** [comment]
> calculate_registration_image_based acts in the same way as other tasks about the input ROI table: it calls convert_indices_to_regions (both for reference/actual cycles) with reset_origin=True (the default argument). It then writes back to the the (actual-cycle) ROI table, after including three new translation_{x,y,z} columns.

Ah, that probably means `calculate_registration_image_based` wouldn't work as expected on non-standard ROIs. 

> apply_registration_to_image calls the convert_indices_to_regions with reset_origin=False, to prepare the relevant array indices. As far as I understand, this is because the registration operation (in the previous task) leads to non-zero-origin ROI tables, and this information is crucial when comparing two cycles (that is, if we reset all origins then we wouldn't know what/where to write data in new arrays)

Yes, exactly. If we want to use ROIs to load registered images (=> that's the output of apply_registration_to_ROI_tables, the registered ROIs), then those ROIs need to be slightly shifted. The only way this can work is that the refer to the same origin as the non-shifted ROI, but their min value isn't necessarily that origin.
Thus, we'd either need an official origin that is read out for each ROI table or to set this origin as 0,0,0.

I'd be in favor of having our current ROIs always be 0,0,0 origins.

Maybe relevant for future developments of this are the approaches used in SpatialData around global coordinate systems or multi coordinate systems: https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/transformations.html
