### ISSUE TITLE
Enable 2D to 3D workflows

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#342]
With recent changes to the server coming with the 1.1.0 release (see https://github.com/fractal-analytics-platform/fractal-server/issues/534 and https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/300), we get closer to have mixed 2D & 3D workflows.

### The goal would be to enable the following workflow:
1. Parse 3D data into OME-Zarr
2. Project to 2D & run cellpose segmentation on larger objects (e.g. organoids) to create new ROI (organoid ROIs)
3. Use those 2D organoid ROIs to segment single nuclei within each organoid back in 3D

### That means:
Being able to run a cellpose task that takes the label image and the ROIs from the 2D Zarr, but takes the image data from the 3D Zarr and stores the result in the 3D Zarr.
When using a ROI from a 2D Zarr on the 3D Zarr, we'd extend along the Z axis from bottom to top.

### Open questions:
- Can we make this work while having the data in 2 different Zarr files or do we need to progress with the work of getting 2D and 3D data stored in the same Ome-Zarr file (I think we already started that discussion somewhere, but can't currently find it)? Many of the challenges should probably be the same, but the implementation would be slightly different for those 2 cases.
- Are there other 2D to 3D workflows? I could imagine a napari-workflow version where we do a similar thing, so the solution shouldn't be too task-specific.

See also discussion around https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/324

**Comment by tcompa** [comment]
This is now in place with fractal V2. Let's re-open specific issues when appropriate.
