### ISSUE TITLE
Test pydantic validation of arguments

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#345]
We should do some sanity checks, in the CI, to catch errors like #343

**Comment by tcompa** [comment]
bec645f52de14afb94e11dc818689d6260fa46a5 adds a test for running a cellpose task via command line, therefore also using pydantic to validate task arguments. Notice that the test is a bit less transparent than its python-function version, because we lost the possibility of using a mocked version of cellpose functions and then we need to rely on other workarounds to avoid a very long-running test.

I verified that this test fails in the current `main` branch.

I don't think it's worth having two versions (python-function-based and script-based) of each single test in the CI tests. But at least we now have an example (well, we already had `test_workflow_executable.py` - which is similar in scope), and it'll be easy to add others when needed (aka when we realize that pydantic argument validation for some tasks is subtle).

**Comment by jluethi** [comment]
Ok, let's add such tests when we do more subtle pydantic validation than the basic types like int, str and such. That sounds like a good trade-off.

And we could slightly expand on `test_workflow_executable.py` at some point to include more of the core tasks to have each tasks go through one test from the command line at least.

**Comment by tcompa** [comment]
Re-opening in view of:
> And we could slightly expand on test_workflow_executable.py at some point to include more of the core tasks to have each tasks go through one test from the command line at least.

**Comment by tcompa** [comment]
As of #369, Pydantic coercion&validation is automatically enabled on all calls to the tasks functions (independently on whether they are made from a script or as Python functions).
This makes it unnecessary to have specific tests for the called-as-a-script case (errors like #343 would have been identified in any test running the cellpose-task Python function).
