### ISSUE TITLE
Add `exclude_glob_patterns` to Create-OME-Zarr task

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#348]
I'm a big fan of the new `image_glob_patterns` for testing & flexibility.
One thing I just thought about: Can we use the `image_glob_patterns` to exclude specific things, e.g. exclude well B05 and B09, but process all others?
If yes, we should document how this can be done. Would be super powerful if e.g. some processing fails because of a specific well has an issue, we could use these glob patterns to exclude that well.

It's already possible to do it by just listing all the wells that are fine, but I'm not sure how I'd do the reverse.

If that's not possible through `image_glob_patterns`, it's a low-priority feature wish for even more flexibility :)

**Comment by tcompa** [comment]
`fnmatch` (as opposed to `re`) has very limited flexibility, and it only offers [`[!seq] | matches any character not in seq`](https://docs.python.org/3/library/fnmatch.html). I tried to build a pattern that would exclude well B05, but I couldn't get one easily. What we could do easily is to exclude all "B" wells, but that's not the intended usecase.

Probably the "trivial" solution is the one that would work best here: we can have two parameters for glob-patterns to include/exclude. That is quite simple to implement (we take the current implementation of multiple glob search, and at the end of it we filter out all matches to any "to-exclude" pattern).

**Comment by tcompa** [comment]
> I tried to build a pattern that would exclude well B05, but I couldn't get one easily.

If someone else wants to try, this is where I got:
```python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> for f in [".._A01_..", ".._A02_..", ".._B01_..", ".._B02_.."]:
...     print(f, fnmatch.fnmatch(f, "*_[!A][0-9][0-9]_*"))
... 
.._A01_.. False
.._A02_.. False
.._B01_.. True
.._B02_.. True
```

**Comment by jluethi** [comment]
> Probably the "trivial" solution is the one that would work best here: we can have two parameters for glob-patterns to include/exclude. That is quite simple to implement (we take the current implementation of multiple glob search, and at the end of it we filter out all matches to any "to-exclude" pattern).

I like this idea. Let's have it as a new feature wish :)
It's not urgent to add this though. The main one is having "include" glob statements
