### ISSUE TITLE
Export arguments JSON schemas somewhere

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#353]

**Comment by tcompa** [comment]
@jluethi @gusqgm @rkpasia 

For the record, the statement `print(TaskArguments.schema_json(indent=2))` in `create_ome_zarr.py` would produce the output below, which is a good starting point for when we'll discuss about using this schema in the web client to define the set of arguments for a WorkflowTask.

Ref: https://github.com/fractal-analytics-platform/fractal-web/issues/63#issuecomment-1473676904


```JSON
{
  "title": "TaskArguments",
  "type": "object",
  "properties": {
    "input_paths": {
      "title": "Input Paths",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "output_path": {
      "title": "Output Path",
      "type": "string"
    },
    "metadata": {
      "title": "Metadata",
      "type": "object"
    },
    "image_extension": {
      "title": "Image Extension",
      "type": "string"
    },
    "image_glob_patterns": {
      "title": "Image Glob Patterns",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "allowed_channels": {
      "title": "Allowed Channels",
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "num_levels": {
      "title": "Num Levels",
      "type": "integer"
    },
    "coarsening_xy": {
      "title": "Coarsening Xy",
      "type": "integer"
    },
    "metadata_table": {
      "title": "Metadata Table",
      "type": "string"
    }
  },
  "required": [
    "input_paths",
    "output_path",
    "metadata",
    "image_extension",
    "allowed_channels"
  ],
  "additionalProperties": false
}
```

**Comment by tcompa** [comment]
Ref:
* https://github.com/fractal-analytics-platform/fractal-server/issues/638
* https://github.com/fractal-analytics-platform/fractal-web/issues/82

**Comment by tcompa** [comment]
From https://github.com/fractal-analytics-platform/fractal-server/issues/638#issuecomment-1516329128:

Agreed, we definitely need improvements on this side (in fractal-tasks-core, IMO). This could be:
* A script that creates the JSON schemas for all tasks in the manifest.
* A test that creates up-to-date schemas (based on the python files) and fails if they don't match with the current ones in the repository.
* A test that compares function arguments to schema entries (or model fields), and fails for any mismatch. This one is actually already needed, even before talking about schemas.

**Comment by jluethi** [comment]
Sounds good, I think such helper functions and tests make sense in this context.

One thing I started wondering about: Do we want to have the json schemas in individual json files per task or should it be part of a (larger) `__FRACTAL_MANIFEST__.json`? If everything got together in the `__FRACTAL_MANIFEST__.json`, there would be 1 file again describing what tasks are present, what their defaults are etc. => maybe easier for validation & tests?

Just started thinking about this from the discussion about dropping the old default_args (that were in the manifest). I'm also fine with schemes in different files per task, just wanted to check that we make a conscious decision about single manifest vs. many json files

**Comment by tcompa** [comment]
As part of #369, the JSON schemas will be stored as part of the manifest, and each task will have a `args_schema` attribute.
