### ISSUE TITLE
Why does napari_workflows_task not return a metadata update?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#357]
The other tasks return either a metadata update or an empty dictionary. As far as I can see, there is no relevant metadata to update (we don't put tables information into the metadata dict), so an empty dictionary may be fine.

**Comment by tcompa** [comment]
You're right, thanks. It should return `{}`.

Note that only non-parallel tasks (e.g. create-ome-zarr) should return useful information via their returned dictionary, while fractal-server ignores the output dictionary of parallel tasks (the reason being that it would be complex to concurrently store the output of multiple parallel executions in the same place).
