### ISSUE TITLE
Can we drop scikit-image<0.20.0 requirement?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#366]
Why do we depend on scikit-image<0.20.0? Is this a requirement we can drop?

Context: I'm working on a scMultipleX task and that library needs to depend on scikit-image>0.20.0

**Comment by jluethi** [comment]
Do you remember any reason we had that version fixed? I don't and can't find anything in a quick github issue search on this repo

**Comment by tcompa** [comment]
> Do you remember any reason we had that version fixed?

I don't.

I think this is simply due to poetry defaults. If I run `poetry add polars` now, I end up with `polars = "^0.17.5"` in `pyproject.toml`. This results in the PyPI package needing a `polars` version `>=0.17.5, <0.18.0` (see [caret dependency definition](https://python-poetry.org/docs/dependency-specification/#caret-requirements)). The same happened for `scikit-image`, which is currently required as `^0.19.3`.

**Comment by jluethi** [comment]
This seems to not have worked as expected yet. I still get `scikit-image==0.19.3` when installing fractal-tasks-core. Maybe one of our dependencies also has this fixed?

**Comment by jluethi** [comment]
Also, I see a warning like this when pip installing the package: `WARNING: Ignoring invalid distribution -cikit-image (/Users/joel/mambaforge/envs/fractal-client-1.2.0a0/lib/python3.9/site-packages)`

**Comment by tcompa** [comment]
I cannot reproduce, can you please add more details?

---

In a fresh venv, if I run `pip install fractal-tasks-core` I get:
```
$ pip show fractal-tasks-core
Name: fractal-tasks-core
Version: 0.9.4
Summary: 
Home-page: https://github.com/fractal-analytics-platform/fractal-tasks-core
Author: Jacopo Nespolo
Author-email: jacopo.nespolo@exact-lab.it
License: BSD-3-Clause
Location: /tmp/env/lib/python3.10/site-packages
Requires: anndata, cellpose, dask, defusedxml, imageio-ffmpeg, llvmlite, lxml, napari-segment-blobs-and-things-with-membranes, napari-skimage-regionprops, napari-tools-menu, napari-workflows, numpy, pandas, Pillow, pydantic, scikit-image, torch, zarr
Required-by: 


$ pip show scikit-image
Name: scikit-image
Version: 0.20.0
Summary: Image processing in Python
Home-page: https://scikit-image.org
Author: 
Author-email: 
...
```

And also https://deps.dev/pypi/fractal-tasks-core/0.9.4/dependencies points to the correct version.

Note that the PyPI package does not _require_ the 0.20 version, but it does _allow_ it. If you download the pypi package, you'll see that:
* The `pyproject.toml` file says `scikit-image = ">=0.19"`;
* The `setup.py` file says `'scikit-image>=0.19'`;
* The `PKG-INFO` file says `Requires-Dist: scikit-image (>=0.19)`.

So all seems in order.

Also in the dev environment, poetry says
```
$ poetry show scikit-image
 name         : scikit-image               
 version      : 0.20.0                     
 description  : Image processing in Python 

dependencies
 - imageio >=2.4.1
 - lazy_loader >=0.1
 - networkx >=2.8
 - numpy >=1.21.1
 - packaging >=20.0
 - pillow >=9.0.1
 - PyWavelets >=1.1.1
 - scipy >=1.8,<1.9.2
 - scipy >=1.8
 - tifffile >=2019.7.26

required by
 - napari >=0.19.1
 - napari-segment-blobs-and-things-with-membranes *
 - napari-skimage-regionprops *
 - ome-zarr *
 - stackview *
```

**Comment by tcompa** [comment]
By the way, if you already know that we do need >=0.20, I can make it a requirement that 0.19 is not allowed.

**Comment by jluethi** [comment]
Hmm, something must have gone funny trying to update things in existing environments. I installed everything fresh this morning and cannot reproduce the warning, nor getting scikit-image 0.19.3 anymore.

Looks like it's fixed, sorry for the time waste here.

(also, fractal-tasks-core doesn't really have a preference on the scikit-image version at the moment => I prefer having this unset. Just the scMultipleX package has requirements and will currently need to depend on fractal-tasks-core)
