### ISSUE TITLE
Handle Yokogawa microscope errors & missing files during multiplexing

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#38]
(Just a backlog issue so that we have a look at this when we start tackling multiplexing)
Handling all possible microscope errors is a bottomless well. Mostly, I think the answer should be to make some checks and inform the user if something is wrong. The user then needs to fix things in order to do the processing. But we should be aware where those errors can come up and what we need to check against.  
If some errors happen often, we may address individual edge cases in the parsing. But let’s do this when we actually hit them, not trying to have the general setup that can handle everything imaginable.

Now, here’s a potential issue that I observed while working on the metadata processing. Would not be an issue for this test set, because it only starts breaking once things are multiplexed, so this is just for the record.

If we parse mlf & mrf files from the Yokogawa, we get messages about where something failed. These are currently parsed & logged (see https://github.com/fractal-analytics-platform/mwe_fractal/issues/46).

-----------

The problem: In our test case XYZ_NAME, we observe an error like this:

Microscope should acquire sites 1-15. Site 3 (and some others) fail, thus it does not image them.

Now we had the following sites: 1, 2, 4, 5 etc

How does the current Zarr parsing handle this?

My assumption:

input site ⇒ # zarr fov number

1 ⇒ 0

2 ⇒ 1

4 ⇒ 2

5 ⇒ 3

If only a single acquisition was taken, I don’t really care about the zarr fov numbering and continuous numbering probably makes things easier for processing & visualization. We anyway save positions in the multiscales metadata (WIP), so sites are positioned correctly.

But now, what if the user would acquire a second acquisiton for the same plate and this time, the microscope does not have an error at site 3?

Then we’d parse:

1 ⇒ 0

2 ⇒ 1

3 ⇒ 2

4 ⇒ 3

5 ⇒ 4

⇒ now the zarr site numbers don’t match over the acquisitions and there will be issues. Plus, the new acquisition has more sites than the original one

Once we actually hit this issue, let’s think about ways of addressing it. In the meantime, the user does get log messages about the errors. Maybe we can have some explicit check for this?

**Comment by tcompa** [comment]
Is this still relevant in the current version? Should we consider it for the current multiplexing image-parsing task or should we wait for #39?

**Comment by jluethi** [comment]
I think we can close this, the main issue has been addressed :)
