### ISSUE TITLE
Split tests into core/tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#391]
After #378, we should also run the tests in two batches: the ones for the core functions, and the ones for the whole package that also include tasks. This will protect us from issues like "I added a cellpose dependency in the core library". Not the most urgent thing to do, but it's always good to improve the tooling of the repo/package.

Note that pytest does offer some kind of test labels (which we would also use to run the CI locally), but we'll still need to properly set up the GitHub action so that:
1. It installs the core part
2. It runs the core tests
3. It install the tasks extra
4. It runs the tasks tests
5. It creates a unique coverage report

**Comment by tcompa** [comment]
Side comment: splitting the tests into core+tasks will also make it clear that some of our core modules require a much more thorough test coverage, e.g. I just realized that lib_masked_loading.py has [a very poor one](https://htmlpreview.github.io/?https://raw.githubusercontent.com/fractal-analytics-platform/fractal-tasks-core/python-coverage-comment-action-data/htmlcov/d_dc89cbc85f94732f_lib_masked_loading_py.html).

For a task, it could be complex to create and maintain test data for all branches, but for the core modules I think we should aim for a very high quality (this is especially true because we plan to have other packages depending on the core part).

**Comment by jluethi** [comment]
Agreed! 

I also just realized how complex this can become for the napari workflows task when looking at the different 2D & 3D branches, those are hard to test exhaustively. But we should aim for high test coverage over our library functions.
