### ISSUE TITLE
Python 3.11 support / llvmlite version

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#392]
As of #390 we will have a core/tasks separation, and also a pip-install GitHub action. This makes it easier to track the support of Python 3.11.

I'll add a new draft PR which only changes the pip-install GitHub action to also include 3.11, so that we can easily identify what is blocking. Sometimes this could be due to very strict requirements on our side, which can maybe relaxed.

For instance, in the latest run, there was an issue with our llvmlite version (see https://github.com/fractal-analytics-platform/fractal-tasks-core/actions/runs/5188089123/jobs/9351257560).
Note that the core package can already be installed with Python 3.11. After #391, we'll likely/maybe be able to run the core CI on Python 3.11 as well.

**Comment by tcompa** [comment]
> After https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/391, we'll likely/maybe be able to run the core CI on Python 3.11 as well.

For the record, this is in-place.

**Comment by jluethi** [comment]
That's great, let's do this!
