### ISSUE TITLE
Update `metadata_table` argument of `create_ome_zarr_multiplex.py`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#432]
Ref:
* https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/399

**Comment by tcompa** [comment]
We should remove the `Union` from `metadata_table`.

What about splitting into two arguments as shown below? (@jluethi)
```python
  @validate_arguments
  def create_ome_zarr_multiplex(
      *,
      input_paths: Sequence[str],
      output_path: str,
      metadata: Dict[str, Any],
      image_extension: str = "tif",
      image_glob_patterns: Optional[list[str]] = None,
      allowed_channels: Dict[str, list[OmeroChannel]],
      num_levels: int = 5,
      coarsening_xy: int = 2,
      default_metadata_table: bool = True,
      metadata_table_files: Optional[dict[str, str]] = None
  ) -> Dict[str, Any]:
```

Then we would implement a check that the two new arguments are mutually exclusive (either you set `default_metadata_table=True` or you provide a non-`None` `metadata_table_files is not None`, but not both at the same time).

**Comment by jluethi** [comment]
Let's simplify it a bit further and drop the `default_metadata_table` & mutually exclusive part.
Just: `metadata_table_files: Optional[dict[str, str]] = None`
If `metadata_table_files` is None => default behavior.
If a user provides them => load the specific metadata tables instead of parsing the metadata.

**Comment by tcompa** [comment]
Agreed.

Should we also rename `metadata_table` (in `create_ome_zarr`) to `metadata_table_file` (with the same logic)?
