### ISSUE TITLE
Move pydantic input schemas to core

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#437]
To encourage broader usage of our Pydantic schemas and avoid that each task defines its own schema (e.g. for input channels), we should move all the pydantic schemas to the core part.

Then, I can depend on fractal-tasks-core (without tasks) also e.g. for the scMultipleX task

**Comment by tcompa** [comment]
Available in 0.10.0a5

**Comment by tcompa** [comment]
(see lib_channels.py, for OmeroChannel and Window, and lib_input_models.py for the others)

**Comment by jluethi** [comment]
Awesome, thanks Tommaso! ❤️
