### ISSUE TITLE
Reorder task inputs in create_ome_zarr, create_ome_zarr_multiplexing

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#450]
Most tasks have the required arguments at the top. For some reason, the Create OME-Zarr and its multiplexing version do not. Let's reorder that unless there is a strong reason for having `Image Extension` & `Image Glob Patterns` above?

For Create OME-Zarr, 2 arguments with defaults come first:
![Screenshot 2023-06-26 at 14 32 08](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/18033446/9ccbe4e3-6426-488b-9855-9f05800d96e0)

For cellpose, the 2 required ones are at the top:
![Screenshot 2023-06-26 at 14 32 11](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/18033446/6397e3bc-619c-4c94-8880-fb08dc3241ab)

**Comment by jluethi** [comment]
I'll review all tasks quickly & would make a PR, unless you disagree @tcompa ?

**Comment by tcompa** [comment]
Go on, thanks!

**Comment by tcompa** [comment]
Closed with #451
