### ISSUE TITLE
Flexibility of args-schema creation tools

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#481]
Placeholder, will complete later.

TL;DR We are modifying the dev tools a bit, recently. We should check that they are still flexible, and work for other packages (e.g. they do not hardcode any information, and they use try/except blocks when appropriate).

**Comment by jluethi** [comment]
It seems to work, I've started to use them in e.g. https://github.com/fmi-basel/gliberal-scMultipleX/pull/96

**Comment by jluethi** [comment]
The only thing I changed was hard-coding the docs-link.
Also using them here this way: https://github.com/jluethi/fractal-faim-hcs/blob/main/src/fractal_faim_hcs/dev/new_args_schema.py
