### ISSUE TITLE
Test multi-plates support

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#49]
Upon parsing of the raw images we are currently identifying all the plates which are available in a given input folder. In current examples there is only one plate, but in principle there could be more. This means that several steps have to be plate-dependent: for instance we need to specify lists of channels/wells/sites for each plate. Later on, during workflow execution, each task should read the lists of channels/wells/sites for the correct plate.

Question: is this really needed? Is there a multi-plate usecase where we really want fractal to handle all of them at the same time?

If there is not a strong motivation for keeping this feature, we propose a simplification where `create_zarr_structure` only handles a single plate. A simple (optional) argument can be used to select a specific plate, if needed (that is, when there are more plates in the same folder). If this argument is not provided, and there are more than one plates, `create_zarr_structure` would raise an exception and fail.

Note that in this way we would loose the automatic parallelizazion over plates, but this seems a very minor issue since we would be mostly parallelizing things across wells (or even sites, if possible).

**Comment by jluethi** [comment]
Our converters are not designed for multi-plate handling. The rest of Fractal shouldn't care much, as tasks that run per image don't know what plate the image is on.
Developing converters that load multiple plates can be a new issue when it comes up
