### ISSUE TITLE
Expand scope of `write_elem` wrapper

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#500]
On the `write_elem` wrapper: can we take this opportunity to make this a broader wrapper that handles more of the table writing? `write_elem` seems like a low level wrapper function. Would be great if tasks can just call a `write_table` or something like that with some parameters. Currently, many task replicate similar handling of the table metadata, updating the list of tables, checking for existing tables etc.

This would be a good opportunity to generalize this and have a useful wrapper that sets the correct metadata for those tables, but that someone building a new task then doesn’t have to think about.

_Originally posted by @jluethi in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/485#issuecomment-1697036561_

**Comment by tcompa** [comment]
Something that clearly can be moved into `write_table` is the creation of the `tables` group (if needed), and the check on whether the required subgroup already exists (to be handled via `overwrite`).

This means that the first version of this function could look like
```python
def write_table(image_group, table_name, table, overwrite=False):
    ...
```

Let's see if we can include more general features in this function.

**Comment by tcompa** [comment]
The first prototype available through https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/f4f127e59de78a8aa0367e9628af306b817dbb19, comments on the scope are welcome.

**Comment by jluethi** [comment]
I like the approach to `write_table` a lot, especially that handling all the metadata attributes now go into a wrapper, not the task function. Will make it much easier to be consistent on those.
I don't fully understand yet how all of them are set and whether we handle e.g. well_ROI_table correctly (see comments). But great that we'll have one place to handle that.

**Comment by tcompa** [comment]
I improved the prototype function (including your suggestion) with  9e5b5e8 and ae459dd0b1448d8593d105588eccf1eb39d64b8b, see current status of PR #499. Let me know if something is still unclear or can be improved.

More changes may come from actually integrating this function in the tasks.
