### ISSUE TITLE
Review `reset_origin=True` implementation in `convert_ROI_table_to_indices`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#507]
As of #487, we'll have a new `reset_origin` helper function, and it'd be best to use that function also within `convert_ROI_table_to_indices` - to avoid duplication. This is a maintenance issue, nothing critical.

Also, depending on #339, we may have to improve/modify this logic in the future.

**Comment by tcompa** [comment]
As part of #524, the `reset_origin` argument is being removed from `convert_ROI_table_to_indices`.

Note that this doesn't mean that we don't reset origins any more, but it rather means that the origin reset is done somewhere else and not any more part of the ROI->indices conversion.
Such change is also instrumental to removing the workaround described in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/339#issuecomment-1460020767.

The origin-reset operation is still present in multiple places, namely in the functions `reset_origin` (which acts on an AnnData table, and is called from `apply_registration_to_ROI_tables.py`) and `_reset_origin_in_dataframe` (which acts on a pandas dataframe, and is only an internal function used by `prepare_FOV_ROI_table` and `prepare_well_ROI_table`).

**Comment by tcompa** [comment]
> The origin-reset operation is still present in multiple places, namely in the functions `reset_origin` (which acts on an AnnData table, and is called from `apply_registration_to_ROI_tables.py`) and `_reset_origin_in_dataframe` (which acts on a pandas dataframe, and is only an internal function used by `prepare_FOV_ROI_table` and `prepare_well_ROI_table`).

As of fcf8391039110e8d9ff489068e78c4669533e689, this was simplified and it is only defined in a single `reset_origin` function.

**Comment by jluethi** [comment]
On the use of reset_origins in `apply_registration_to_ROI_tables.py`:
If all tables already come with a reset origin, then this is not necessary anymore. We only needed to run reset_origins because FOV & well ROIs had non-0 origins.
