### ISSUE TITLE
Improve `OverwriteNotAllowedError` error messages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#512]
Those are sometimes very long strings (due to absolute paths), and the relevant information is hidden at the end.

**Comment by tcompa** [comment]
This is how things look in version `0.11.0a2` in fractal-web (as of #515). There is still room for improvement, but at least the "Hint" sentence is now visible:

![Screenshot from 2023-09-12 13-20-30](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/cbebf3d5-d413-4c4d-8e48-ffd9019543fe)

**Comment by jluethi** [comment]
That's a good start! :)
