### ISSUE TITLE
Update new datasets to Zenodo

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#526]
As soon as #524 is merged (ref #339), the existing zarr datasets on Zenodo will be "wrong", in that they still have ROI tables with non-zero origins.

Through f2bb44f4ceabe0c15c4e4449c522bb33c900c370, we are fixing this issue with a workaround in the CI: after downloading from Zenodo, we load the FOV/well ROI tables and shift them by hand.

To do:
- [x] Update Zarr datasets
- [x] Remove workaround from pytest fixture

**Comment by jluethi** [comment]
And the example 02 dataset (the 2x2 FOV example) is now available here: https://zenodo.org/records/10257532

**Comment by tcompa** [comment]
Thanks!

> We should also update the links on the Fractal splash page to point to this new Zenodo dataset now

Done.

> Do we link to them from anywhere else?

Not that I'm aware of.

---

I'm closing this issue with #623, that removes the original workaround related to ROI-origin-shift.

Note that it's be good to update datasets once again, after #613 is merged and released. Even if the current one were generated with v0.14.0a0, they probably still lack some metadata:
![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/a16889ca-753f-4cd0-808e-e372cceadfd3)
