### ISSUE TITLE
List tasks from public packages using fractal-tasks-core

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#599]
I am currently aware of:
* https://github.com/fmi-basel/gliberal-scMultipleX
* https://github.com/jluethi/fractal-faim-hcs
* https://github.com/MaksHess/abbott

**Comment by jluethi** [comment]
I’ve been thinking about having a page of all the repos that provide Fractal tasks. This may not be a 1-to-1 overlap with packages depending on fractal-tasks-core, but a subset of them.
Having a page that either lists all and highlights the ones providing tasks (e.g. the ones with a task manifest) or just having one with the packages that provide tasks would be valuable indeed!

**Comment by tcompa** [comment]
This is an example of how it would look like from within #625:

![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/daa0a5de-80ff-430a-9493-6e4167c9b16a)

Feedback is welcome.

---

As usual, one can render the docs locally through
```
git checkout 599-should-we-list-public-packages-using-fractal-tasks-core-in-the-docs
git pull
poetry install --with docs
poetry run mkdocs serve --config-file mkdocs.yml --dev-addr localhost:8001
# ...
# INFO    -  [11:43:48] Browser connected: http://localhost:8001/
```

**Comment by jluethi** [comment]
Nice! Can we add a "Want to build your own task => follow the instructions here"
And a comment on "it's the list of tasks we're aware of on 5/12/2023. You created your own Fractal task that comes as a package? Reach out to have it listed here."

I'll review further and add more things later :)
Will be nice to give a shout-out to who is building those tasks explicitly as well.

**Comment by tcompa** [comment]
Here is how it looks now in #625.
Is there anything more to add? (apart from reaching out to the actual maintainers)

![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/27207aae-56ce-4864-8c67-01b153b96cdc)

**Comment by jluethi** [comment]
Looks good to me. Let's merge and I'll contact the maintainers :)
