### ISSUE TITLE
Update Zenodo datasets with v0.14.0

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#624]
Note that it'd be good to update datasets once again, after #613 is merged and released. Even if the current one were generated with v0.14.0a0, they probably still lack some metadata:
![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/a16889ca-753f-4cd0-808e-e372cceadfd3)

_Originally posted by @tcompa in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/526#issuecomment-1840364069_

**Comment by jluethi** [comment]
I had already included those, so it's 0.14.0a0*. But yes, let's re-release when we have the real 0.14.0 release :) And then link to those from the different pages

**Comment by jluethi** [comment]
@tcompa My understanding is that nothing changed anymore in those datasets after I uploaded them. Are there any issues that still need to be fixed in them?

**Comment by tcompa** [comment]
If the current dataset include 1361c79117bbf1c092e54fecaadb299f1b79c2a0 (that is, the non-masking ROI table have the correct `type` attribute), then I think none of the subsequent commits made any difference of what would be written in the tables' contents or attributes.
