### ISSUE TITLE
Improved standardization of ROI table obs namings?

### ISSUE THREAD

**Issue by nrepina** [fractal-analytics-platform/fractal-tasks-core#629]
I’m finding some inconsistencies with how the obs in anndata is saved for FOV ROI tables vs. organoid ROI tables. See below:

**FOV ROI table:**
print(r0_adata.obs_names, r0_adata.obs_keys(), r0_adata.obs.columns)

Index(['FOV_7'], dtype='object', name='FieldIndex') 
[] 
Index([], dtype='object')

**organoid ROI table:**
print(r0_adata.obs_names, r0_adata.obs_keys(), r0_adata.obs.columns)

Index(['0', '1', '2'], dtype='object') 
['label'] 
Index(['label'], dtype='object')

As you see for FOV there is no key for obs which makes it more difficult to index into the obs values, whereas for the organoid table we have the ‘label’ key. Would it be possible to standardize? 

The reason a key would be helpful is that the only way I’ve found to read an obs column into a numpy array directly from adata is using r0_adata.obs_vector(‘label’), which goes by key; if there’s no key I need to do a work-around with converting all of obs into a pandas df, then correct naming, and convert to a numpyarray. But maybe there’s something I’m missing and there’s another way with anndata! Let's discuss :)

**Comment by jluethi** [comment]
Hey @nrepina 

Tommaso and I had a quick look today. I don't currently think it's necessary to add index names to the AnnData tables more broadly. You can easily access the list of indices without knowing the index name in the following way:

```
import anndata as ad
table = ad.read_zarr(path)
print(table.obs_names)
Index(['FOV_1', 'FOV_2'], dtype='object', name='FieldIndex')

print(table.obs_names.to_numpy())
array(['FOV_1', 'FOV_2'], dtype=object)

```

=> using `table.obs_names.to_numpy()` should work for FOV tables and ROI tables.
If you want, you can add a check on the dimensions of that array (should be (n,), with n as the number of rows in your array, and only 1-d). 
If we ever were to start to have multi-indices in ROI table obs / other table obs (not sure why we would), then that would need to generalize. Until then, access via `.to_numpy()` seems fine to me.


Is there anything you'd think isn't covered with that?
