### ISSUE TITLE
Write version in plate attributes

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#676]
Our current converters are not writing a version in the plate .zattrs. Not sure why our validation still passes with this, but the spec specifies:

> The plate dictionary MUST contain a version key whose value MUST be a string specifying the version of the plate specification.

https://ngff.openmicroscopy.org/latest/index.html#plate-md

**Comment by tcompa** [comment]
> Not sure why our validation still passes with this,

I guess it's because `version` is not marked as required in the NGFF JSON Schemas (https://github.com/ome/ngff/blob/main/0.4/schemas/plate.schema#L135-L137):
```json
      "required": [
        "columns", "rows", "wells"
      ]
```

**Comment by jluethi** [comment]
Ah, I now realised:
The 0.4 spec says it SHOULD contain a version key. Only the current latest 0.5-dev is switching this to MUST.

In any case, I think it's a really good idea that it does contain one! I'll be adding it in the 1.0 refactor now

**Comment by jluethi** [comment]
This was implemented in https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/671
We now always write the version. But our NGFF validator still has it as Optional, as it's not required in 0.4 yet.
