### ISSUE TITLE
Order of task arguments in the schema

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#691]
We should go back to order the arguments as they appear in the function, not alphabetically. Currently, the schema has them ordered alphabetically, which leads to a web interface that orders them the same (& is not a clean user-experience)

<img width="1519" alt="Screenshot 2024-04-11 at 13 38 03" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/07b31177-0cf2-4bd6-82b7-b9ad24ea95c1">

**Comment by tcompa** [comment]
My bad (ref https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/671/commits/cf8365aac21164fdcaa70c0890ca5aa635f036fa). I'll revert this change.
