### ISSUE TITLE
Add test that validates NGFF metadata after copy-ome-zarr

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#694]
Ref https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/bffe65aff13671abb133db4e96a46e4bff26ef53

**Comment by jluethi** [comment]
We already have a test in place to validate the NGFF metadata for images, wells & plates after MIP, see:

https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/1d1e9657e2ea7c18e0aa79923719d093520c66b0/tests/tasks/test_workflows.py#L393-L399

I also checked the outputs of example 01 & 02 and the metadata appears valid. Some workflows that rely on plate & well metadata like registration also run successfully after MIP.

**Comment by tcompa** [comment]
> We already have a test in place to validate the NGFF metadata for images, wells & plates after MIP, see:

This test did not catch https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/bffe65aff13671abb133db4e96a46e4bff26ef53, because the `well` attribute is not required by the JSON Schema and arbitrary attributes are allowed.

I made tests a bit more strict with https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/732. Note that having a well group without a `well` attribute would be specs-compliant, but it's not very relevant within our tests.
