### ISSUE TITLE
Add illumination correction to the list of registered tasks

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#70]
Currently, illumination correction isn't in the list of tasks here: https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/d3dfdc84372513232f08032da52d6649379b0c44/fractal_tasks_core/__init__.py

Once we have the ROI implementation (https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/27), let's add it to the list, so we can easily test it as part of large pipelines.

**Comment by tcompa** [comment]
No real reason to wait for the new ROI implementation.
I've added it to the manifest with some very basic defaults (but not tested it here yet, since that kind of testing should happen within the other fractal components).
