### ISSUE TITLE
Use zarr's regions in illumination correction

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#75]
I'm branching from https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/27, to have a clean discussion. I'll try to report here only the progress related to the illumination-correction task.

**Comment by tcompa** [comment]
As of https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/d69aef99f5fc087bccc98f8726f5e02ad0df9412, we have a `Sandbox_zarr_regions` folder with `run_example_long.py`, which I will run on our typical test dataset (single-well, 2x2 FOVs, 10 Z planes, 3 channels). To make tests more compelling, I'm always starting from a previously generated reference zarr folder.
The mprof profile, before any change to the task, looks like
![fig](https://user-images.githubusercontent.com/3862206/190359152-1dcd0d84-ea01-487d-ae5e-a148840580c6.png)

Before starting changing the task, I'll also prepare a test with a larger dataset, since this one may be too small (616 M, at level 0) to observe the problem we are tackling here.

**Comment by jluethi** [comment]
Larger tests are a great idea, it is much easier to see there. `/data/active/fractal/3D/PelkmansLab/CardiacMultiplexing/Cycle1_9x8_singleWell` would be a compelling large example, as it has only 1 well, but 72 FOVs in that well (see https://github.com/fractal-analytics-platform/fractal/issues/213 for details)

**Comment by tcompa** [comment]
That's the one I'm planning to use.

**Comment by tcompa** [comment]
I've set up an example with
* One well
* 72 FOVs
* 3 channels
* 10 Z planes
* About 12G on disk for the highest-resolution level

As of https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/4f9aad1bbde2b116701a119b1b6330009f57330b (without any actual change to the task), this is the memory usage:

![fig](https://user-images.githubusercontent.com/3862206/190399557-3827f48a-2718-415b-a279-fa1ea900df78.png)

**Comment by tcompa** [comment]
Also https://github.com/dask/dask/issues/8460 (unfortunately still open) is quite relevant for dask masks (that are required for background subtraction).

**Comment by tcompa** [comment]
The new approach of using regions/tasks means that the input of `correct()` (or any other function, for tasks with a similar structure as `illumination_correction`) is a dask array, rather than a numpy one. This makes some operations more difficult, notably the use of masks as in
```
array[array > threshold] = array[array > threshold] - background
```
The reason for this is that the result of masking has some unknown properties (e.g. the chunks), and then dask cannot proceed.

As a first version (https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/8763527f959869bf38629dc7534e8ac1943855ba), I've chosen to transform the input and output explicitly so that the function only works with numpy arrays:
```
def correct(dask_array, ...):
    np_array = dask_array.compute()
    ...
    return da.array(np_array)
```

By now this is only a workaround, for several reasons: (1) it makes parallelism (which we may want, in the future) impossible or at least much harder, (2) it adds some overhead for two array conversions. If we ever think that this is the way to go, we need to think about it more carefully.

Still, preliminary benchmarks show that the memory is under control:
![fig](https://user-images.githubusercontent.com/3862206/190418473-2caac5b1-8d84-4484-a17c-d9a004350b4a.png)


Notice that the task used for this test still lacks a lot of functionalities.. More updates in due time.

**Comment by tcompa** [comment]
This block of code does what it is supposed to do (background subtraction for dask arrays):
```python
import dask.array as da
import numpy as np

def subtract_background(array, background):
    x_with_sign = x.astype(np.int16)
    x_with_sign = x_with_sign - background
    x_with_sign[x_with_sign < 0] = 0
    return x_with_sign.astype(np.uint16)

x = da.arange(16, dtype=np.uint16).reshape((4, 4))
new_x = subtract_background(x, 5)
print(x.compute())
print(new_x.compute())
```

The only missing part here would be how to make it general (uint8 -> int8, uint16 -> int16, ...)

**Comment by jluethi** [comment]
Hmm, very interesting point you're raising. We can likely do something like your dask background subtraction approach to keep this dask compatible

**Comment by jluethi** [comment]
Hmm, very interesting point you're raising!

First of all, very nice to see how nice memory is under control and that the runtime remained constant!
Also, nice dask workaround with the background subtraction, a bit annoying that we're hitting these kind of limits. I guess for illumination correction, we could get away with a refactor to have it run on dask arrays.

But for other things, I'm thinking especially about the napari workflows, but also tasks lab members may write, we can't know whether they will be dask compatible or require a numpy array. Thus, I think we should invest the time to write this in a way that gives (delayed) numpy arrays to the actual function (e.g. to correct). Does doing a numpy conversion force the dask array to be computed or can we set this up delayed? Using the regions approach, we also wouldn't necessarily have to convert the output back to dask, right? We could just pass the delayed object to the `to_zarr` function with a fitting `region` parameter.

@tcompa Given that this could have larger implications for general task design & workflow wrapping, let's talk about this briefly tomorrow

**Comment by tcompa** [comment]
After discussing with @mfranzon and @jluethi, we opted for

* **Technical decision 1**: we'll proceed with a fully sequential scan of ROIs. This simplifies things a lot for when we (or a user) have to define the `correct` function (or equivalent), because its I/O will both be numpy arrays.
* **Technical decision 2**: we assume that a full FOV array (e.g. with shape 10x2160x2560, or even 100x2160x2560) can fit in memory, and we design the processing functions (loading images, illumination correction, segmentation) such that they work on this kind of arrays. In some cases (loading images, illumination correction) there are easy ways to work with 2D images, but we stick with the general approach. This is relevant also for #72.



The current version (https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/5b61cd90a469e615acf56e99eaeda21fd70d31ef) then has code like:
```python
def correct(
    img_stack: np.ndarray,
    corr_img: np.ndarray,
    background: int = 110,
    logger: logging.Logger = None,
):
    ...
    # return a numpy array

def illumination_correction(...):
...
    # Create zarr for output
    new_zarr = zarr.create(
        shape=data_czyx.shape,
        chunks=data_czyx.chunksize,
        dtype=data_czyx.dtype,
        store=da.core.get_mapper(newzarrurl + "/0"),
        overwrite=False,
        dimension_separator="/",
    )

    # Iterate over FOV ROIs
    for i_c, channel in enumerate(chl_list):
        for indices in list_indices:
            # Define region
            s_z, e_z, s_y, e_y, s_x, e_x = indices[:]
            region = (
                slice(i_c, i_c + 1),
                slice(s_z, e_z),
                slice(s_y, e_y),
                slice(s_x, e_x),
            )
            # Execute illumination correction
            corrected_fov = correct(
                data_czyx[region].compute(),
                corrections[channel],
                background=background,
                logger=logger,
            )
            # Write to disk
            da.array(corrected_fov).to_zarr(
                url=new_zarr,
                region=region,
                compute=True,
            )
```

The corresponding memory profile is shown below. Notice that we are now computing 3D arrays, so that it is obviously more memory-expensive than in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/75#issuecomment-1248117817. 

![fig](https://user-images.githubusercontent.com/3862206/190594207-96efd720-79b0-4ab3-addc-d646795e6283.png)


**Additional comment on memory usage**:
The fact that scaling is sublinear (we have 10-times-larger arrays than before, but only oughly 3-times-larger memory), together with the fact that the expected array size is quite smaller than the memory usage
```python
>>> np.random.randint(100, 1000, (10, 2160, 2560)).astype(np.float64).nbytes / 1e6
442.368
```
suggest that a relevant fraction of the memory usage is additional overhead, rather than scaling with array size.

**Comment by tcompa** [comment]
Feedback on the previous comment is welcome (@jluethi @mfranzon). Meanwhile, I'll start putting back in the task all the features that I had taken away for testing purposes.

**Comment by jluethi** [comment]
This is awesome @tcompa ! Very cool memory usage graph!

As we discussed, I support technical decisions 1 & 2, I think those are very reasonable trade-offs to make to get things running and to keep it simple. The memory usage in this illumination correction example looks good, this is certainly something that could go into production. And fascinating to see this sublinear scaling :)

The memory usage does highlight though how things will change with ROI sizes. Relevant for https://github.com/fractal-analytics-platform/fractal-server/issues/34. Let's still proceed as planned there, but let's keep evaluating when we hit more real example data and real performance & memory profiles.

Regarding the parsing to Zarr (https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/72): Is the plan to also do that in 3D? While this should mostly work, I think the reason to go 3D there right away is less strong (not `compute` function that takes numpy arrays is required). And because everyone will always have to run parsing to get the data into OME-Zarr + that can run for a while given the IO, I think it's worth it to write that in the somewhat more memory efficient 2D approach. Let's have the discussion in the other issue. If 2D parsing does get too complex, it's not blocking to do it in 3D. But let's see if we can get this running as a memory-optimized 2D workflow :)

**Comment by tcompa** [comment]
With the current commit (https://github.com/fractal-analytics-platform/fractal-tasks-core/commit/c74ca262639fe7bc724be09a114fb9a848bb751e), we support both `overwrite=True` and `overwrite=False`. In the latter case, an additional argument `new_component` (with the same form as `component`) is required. We can later streamline/improve this interface, if needed.

**Comment by jluethi** [comment]
Great! Refactoring for streamlines usage of `overwrite=False` may become interesting in the context of workflow flexibility (https://github.com/fractal-analytics-platform/fractal/milestone/10). But for the current milestone, this is great! 🎉
