### ISSUE TITLE
Add APX package to the task list on doc page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#752]
Let's also add the APX package to the list of task packages: https://github.com/Apricot-Therapeutics/APx_fractal_task_collection

Given that it has a long list of somewhat evolving tasks: Do we just link to the package for the list of available tasks?

@adrtsc Would you be fine with APX showing up here? https://fractal-analytics-platform.github.io/fractal-tasks-core/all_tasks/
Would you have a summary of the package scope? e.g. this package provides converters for IC6K, tasks for X etc.

**Comment by tcompa** [comment]
> Given that it has a long list of somewhat evolving tasks: Do we just link to the package for the list of available tasks?

There is no problem in updating the list automatically before building the docs on GitHub, as introduced in #759:

![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/ff2b037e-809a-44b8-9660-e9d28e601875)

---

>  Would you have a summary of the package scope? e.g. this package provides converters for IC6K, tasks for X etc.

As of #759, we support adding a `description` field to the package.

**Comment by adrtsc** [comment]
Would be great to have the APx collection show up there! As for the scope, maybe the initial paragraph of the github README would be enough:

> The APx Fractal Task Collection is mainainted by [Apricot Therapeutics AG](https://apricotx.com/), Switzerland. This is a collection of tasks intended to be used in combination with the [Fractal Analytics Platform](https://github.com/fractal-analytics-platform) maintained by the [BioVisionCenter Zurich](https://www.biovisioncenter.uzh.ch/en.html) (co-founded by the Friedrich Miescher Institute and the University of Zurich). The tasks in this collection are focused on extending Fractal's capabilities of processing 2D image data, with a special focus on multiplexed 2D image data. Most tasks work with 3D image data, but they have not specifically been developed for this scenario.

**Comment by tcompa** [comment]
OK, thanks!

This is how it would look, as of #759 (and with the new description)
![image](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/d0f45d5d-8c20-4ca4-900e-867b4ccc38cc)
