### ISSUE TITLE
Use new Zenodo datasets in tests

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#753]
WIP list of updates needed.

For https://zenodo.org/records/10257532:

- [x] Update to 2.0 workflow

For https://zenodo.org/records/10257149

- [x] Update to 2.0 workflow

**Comment by jluethi** [comment]
The new tiny OME-Zarr dataset is available here: https://zenodo.org/records/13305156

The new small OME-Zarr dataset is available here: https://zenodo.org/records/13305316

cc @lorenzocerrone These test datasets now include masking ROI tables :)

@tcompa Can you update our test cases to use these new datasets?

**Comment by lorenzocerrone** [comment]
@jluethi Thanks super useful for Ngio
