### ISSUE TITLE
Set the OMERO format version consistently

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#77]
Currently, part of the .zattrs have version 0.3 and other parts have version 0.4 specified. We are actually using something that is closer to the not-yet-released version 0.5 (using AnnData tables), but we shouldn't specify that yet (not sure the readers would work with a version that hasn't been released).

Thus, when we open the OME-Zarr files in napari, we get these kind of warnings:
```
17:02:39 WARNING version mismatch: detected:FormatV03, requested:FormatV04
17:02:41 WARNING version mismatch: detected:FormatV04, requested:FormatV03
```

We should:
- [ ] Set the versions consistently
- [ ] Have a single variable (or at least a variable per file) instead of hard-coded version numbers to make adapting the version easier in the future

**Comment by tcompa** [comment]
This can now be retrieved as
```python
import fractal_tasks_core
print(fractal_tasks_core.__OME_NGFF_VERSION__)
```
and it is currently set to `0.4`.
