### ISSUE TITLE
Add operio-fractal to task list on doc page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#776]
Let's add the new operio-fractal package available at https://github.com/leukemia-kispi/operetta-compose by @fdsteffen to the list of available tasks on the Fractal tasks doc page: https://fractal-analytics-platform.github.io/fractal-tasks-core/all_tasks/

**Comment by tcompa** [comment]
Should we also provide a description field?

**Comment by jluethi** [comment]
Let's take this description from the README initially:

> Fractal tasks for the Opera/Operetta microscope and drug response profiling

**Comment by tcompa** [comment]
See https://fractal-analytics-platform.github.io/fractal-tasks-core/all_tasks/#operio-fractal
