### ISSUE TITLE
Make our OME-Zarr creation compliant with the v0.4 OME-NGFF spec

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#78]
I got feedback form the OME-Zarr devs now that we have a first OME-Zarr dataset on Zenodo here: https://doi.org/10.5281/zenodo.7081622

Our current OME-Zarr file isn't fully v0.4 spec compliant yet. They actually have a web validation tool they run to check this and that website can flag errors. See details in the quote below.

Let's make sure we become v0.4 compliant, because we're already using some parts (e.g. tables) that will be v0.5. Besides being explicit with the version and setting it consistently (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/77), that will mean ensuring we have all the necessary parameters specified, like `rowIndex` and probably more that will come up when we test this.

Let's use the https://ome.github.io/ome-ngff-validator tool to check what we're missing until our OME-Zarr files pass that check.

Here's how Will describes using the tool:
> Will Moore: I served the data locally then used https://ome.github.io/ome-ngff-validator
> E.g. https://ome.github.io/ome-ngff-validator/?source=http://localhost:8000/zenodo/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr
> 
> Will Moore: That validates it against the JSON schema at https://raw.githubusercontent.com/ome/ngff/main/0.4/schemas/plate.schema
> 
> Will Moore: Which gave me:
> ```
> {
>   "instancePath": "/plate/wells/0",
>   "schemaPath": "#/properties/plate/properties/wells/items/required",
>   "keyword": "required",
>   "params": {
>     "missingProperty": "rowIndex"
>   },
>   "message": "must have required property 'rowIndex'"
> }
> ```
> Will Moore: This really fails because there's no plate.version, so it's defaulting to "0.4".
> 
> Will Moore: If you include "plate": {"version": "0.3"} it validates fine
> Will Moore: However, the multiscales image itself does have "version":"0.3".
> For v0.3, the axes must be a list of strings: https://ngff.openmicroscopy.org/0.3/index.html#multiscale-md but you have used the "0.4" spec here with axes being objects
> 
> Will Moore: So https://ome.github.io/ome-ngff-validator/?source=http://localhost:8000/zenodo/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/ gives me
> ```
> {
>   "instancePath": "/multiscales/0/axes/0",
>   "schemaPath": "#/properties/multiscales/items/properties/axes/items/type",
>   "keyword": "type",
>   "params": {
>     "type": "string"
>   },
>   "message": "must be string"
> }
> ```

**Comment by jluethi** [comment]
Oh, and we can even check like this:
```
$ git clone git@github.com:ome/ngff.git
$ pip install jsonschema
$ jsonschema --instance /path/to/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/.zattrs 0.4/schemas/plate.schema
0.3: '0.3' is not one of ['0.4']
{'path': 'B/03'}: 'rowIndex' is a required property
{'path': 'B/03'}: 'columnIndex' is a required property
```

Thanks to Will Moore for the details here :)

**Comment by tcompa** [comment]
I added `test_ngff_schema.py` to the CI, so that now we verify that the output of a test workflow is compliant with the ome-ngff version in use (as stored in `fractal_tasks_core.__OME_NGFF_VERSION__`). The validation is performed for the plate/well/image `.zattrs` files.

To do:
- [ ] At the moment the workflow only parses images to a zarr. We should include a more complex workflow (e.g. with a MIP), to validate zarr-structure replication.
- [ ] We should also validate labels.

**Comment by tcompa** [comment]
I'm moving this to #86, since I want to move on with merging/testing/releasing.
