### ISSUE TITLE
Improve type hints and docstring for calculate_registration_image_based

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#797]
In terms of type hints, I think we should move from
```python
method: RegistrationMethod = "phase_cross_correlation"
```
to
```python
method: RegistrationMethod = RegistrationMethod.PHASE_CROSS_CORRELATION
```

---

In terms of docstrings, I think we should include a docstring like
```python
class RegistrationMethod(Enum):
    """
    Description

    Attributes:
        PHASE_CROSS_CORRELATION: something
        CHI2_SHIFT: something
    """
```

(which is useful as part of work on new manifest generation)

I'll do this as a separate PR, to keep it independent from some other ongoing work.

**Comment by jluethi** [comment]
Sounds reasonable. Will those docstrings show up in the dropdown of the selector in Fractal web afterwards? In that case, I'd argue for
```
Attributes:
        PHASE_CROSS_CORRELATION: phase cross correlation
        CHI2_SHIFT: chi2 shift
```

If we want longer docstrings, we can go with something like:

```
Attributes:
        PHASE_CROSS_CORRELATION: phase cross correlation based on scikit-image. 
        CHI2_SHIFT: chi2 shift based on image-registration library.
```

**Comment by tcompa** [comment]
> Will those docstrings show up in the dropdown of the selector in Fractal web afterwards?
Not in the current version, where the only Info button is the one related to the argument itself, with message like "Method to use for image registration. The available methods are `phase_cross_correlation` (scikit-image package, works for 2D & 3D) and "chi2_shift" (image_registration package, only works for 2D images).":
![image](https://github.com/user-attachments/assets/e1556e49-5b49-4992-951b-05b1e48721bb)


That said, thanks for providing reasonable docstrings - I'll include those.

**Comment by jluethi** [comment]
Ah actually, we should keep the wording that says chi2_shift only supports 2D images. That's probably the most relevant part of the docstring 🙈

**Comment by tcompa** [comment]
This description:

> "Method to use for image registration. The available methods are phase_cross_correlation (scikit-image package, works for 2D & 3D) and "chi2_shift" (image_registration package, only works for 2D images).":

is the one for the `method` argument, and I'm not changing it. It is also the only one that appears in fractal-web.

The Enum attribute descriptions are not currently displayed anywhere, but I'll still include the 2D-support info in there (in case someone reads the source code).
