### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#804]
I'll release 1.1.1, so that we are ready for merging #793 and releasing it as 1.2.0.

Version 1.1.1 doesn't need to reach any actual Fractal instance, but it's good to have it as a fallback and as a last-valid-release in case someone hits any Pydantic V2 issues.

The 1.1.1 CHANGELOG is as follows

* Tasks:
    * Fix issue with masked ROI & relabeling in Cellpose task (\#785).
    * Fix issue with masking ROI label types in `masked_loading_wrapper` for Cellpose task (\#785).
    * Enable workaround to support yx images in Cellpose task (\#789).
    * Fix error handling in `calculate_registration_image_based` (\#799).
    * Fix minor issues with call-signature and type hints in `calculate_registration_image_based` (\#799).

**Comment by jluethi** [comment]
Sounds good! :)
