### ISSUE TITLE
Review image-plate attribute of MIP task

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#841]
While working on https://github.com/fractal-analytics-platform/fractal-web/issues/553, I noticed that the images pre- and post-projection are listed with an identical "plate" attribute:
![image](https://github.com/user-attachments/assets/3854671c-871c-400f-b232-06337aca436a)

Is this the expected behavior, or should we change it for the projected images?

**Comment by jluethi** [comment]
Oh, that's an interesting question!

I can really see this being argued either way.

My initial reaction is: We should list the mip plate as 20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr to make those distinct.

But one could argue it's really the same plate, just with a different `is_3D property`
