### ISSUE TITLE
Review failed test for BIA data 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#878]
We've been hitting this test failure for a few days:
```
FAILED tests/tasks/test_import_ome_zarr.py::test_import_ome_zarr_image_BIA - TimeoutError: [Errno 60] Operation timed out
```
The failure has to do with FTP access to BIA

```
        # Download an existing OME-Zarr from BIA
        ftp = FTP("ftp.ebi.ac.uk")
        ftp.login()
        ftp.cwd("biostudies/fire/S-BIAD/843/S-BIAD843/Files")
        fname = "WD1_15-02_WT_confocalonly.ome.zarr.zip"
        with (tmp_path / fname).open("wb") as fp:
>           ftp.retrbinary(f"RETR {fname}", fp.write)

tests/tasks/test_import_ome_zarr.py:290: 
```
which fails with a `TimeoutError`.

This was a `ConnectionRefusedError` a few days back - see https://github.com/fractal-analytics-platform/fractal-tasks-core/actions/runs/12253006499/job/34183395372.

**Comment by jluethi** [comment]
Do we run this test regularly? I thought we had the BIA tested disabled to avoid such potential issues?
