### ISSUE TITLE
Refactor metadata reading to scale better for huge datasets

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#94]
While working on #30, it would be useful to access the 23-wells example, but metadata files are missing in `/data/active/jluethi/20200810-CardiomyocyteDifferentiation14/Cycle1/images_renamed/`.

@jluethi, how should we proceed?
If this is something you can add, great.
If not, is there another available large dataset with metadata? (there is none in https://github.com/fractal-analytics-platform/fractal/issues/213)

Those would be the ideal cases, otherwise we will first have to go through https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/47.

**Comment by jluethi** [comment]
I'll have a quick look at this tomorrow, maybe I can find a way to correctly fake this metadata at the scale of the full experiment. If I can't find an easy way to get there, solving #47 will be easier (as I'd have to go through the whole logic we will need for #47 plus more for additional metadata lines in that file).

**Comment by jluethi** [comment]
I now created the metadata for the 23 well case and also put it in this folder here: `/data/active/jluethi/20200810-CardiomyocyteDifferentiation14/Cycle1/images_renamed/`. I had to doctor with it a bit (change all the timepoints to the newly correct timepoints, remove some parts that were imaged but not part of the dataset in the folder). 

The file looks correct, but parsing appears to be very slow (> 10 min in some local tests). I'm currently debugging this to figure out if the parsing function doesn't scale well to that size of metadata files or if there is some issue with the actual metadata file I created here.

**Comment by jluethi** [comment]
Ok, the metadata parsing ran through now. Our current parsing function seems to process the metadata correctly, but it scales very poorly. Parsing of the metadata took 54 minutes.

Something scales worse than O(n) in our current parsing. This metadata file contains 163512 entries, parsing takes 54 minutes.
The metadata file for a single well with 4104 entries (40x fewer entries) is parsed in about 6 seconds (about 540 times faster).
=> When scaling up 40x, we become 540x slower
=> We'll need to profile the metadata parsing to make this faster. It's usable if we want to run the 23 well example (that anyway takes hours to run), but there is very clear optimization potential!

**Comment by tcompa** [comment]
Food for thought : let's also consider https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html (unless you already did).

**Comment by jluethi** [comment]
Very interesting, thanks for linking to that! No, I haven't looked at it. My first tests point to the actual reading not being the limiting step (as expected, even the huge metadata file is "only" 60 MB). But maybe the downstream processing of it and the aggregation would go much faster with the pandas xml reader than the current defusedxml approach :)

**Comment by tcompa** [comment]
Reading the 60M file with
```
x = pd.read_xml("MeasurementData.mlf")
```
takes less than 8 seconds (locally) and yields a table like
```
       Type                           Time  Column  Row  TimePoint  FieldIndex  ZIndex  TimelineIndex  ActionIndex Action       X       Y     Z  Ch                                  MeasurementRecord
0       IMG  2020-08-12T17:36:36.234+02:00       3    2          1           1       1              1            1     3D -1448.3  1517.7  -2.0   1  20200812-CardiomyocyteDifferentiation14-Cycle1...
1       IMG  2020-08-12T17:36:36.234+02:00       3    2          1           1       1              1            1     3D -1448.3  1517.7  -2.0   2  20200812-CardiomyocyteDifferentiation14-Cycle1...
2       IMG  2020-08-12T17:36:36.519+02:00       3    2          1           1       2              1            1     3D -1448.3  1517.7  -1.0   1  20200812-CardiomyocyteDifferentiation14-Cycle1...
3       IMG  2020-08-12T17:36:36.519+02:00       3    2          1           1       2              1            1     3D -1448.3  1517.7  -1.0   2  20200812-CardiomyocyteDifferentiation14-Cycle1...
4       IMG  2020-08-12T17:36:36.802+02:00       3    2          1           1       3              1            1     3D -1448.3  1517.7   0.0   1  20200812-CardiomyocyteDifferentiation14-Cycle1...
...     ...                            ...     ...  ...        ...         ...     ...            ...          ...    ...     ...     ...   ...  ..                                                ...
163507  IMG  2020-08-13T03:20:15.779+02:00       8    7          1          72      15              4            2     3D  1463.6 -1290.2  12.0   3  20200812-CardiomyocyteDifferentiation14-Cycle1...
163508  IMG  2020-08-13T03:20:15.956+02:00       8    7          1          72      16              4            2     3D  1463.6 -1290.2  13.0   3  20200812-CardiomyocyteDifferentiation14-Cycle1...
163509  IMG  2020-08-13T03:20:16.134+02:00       8    7          1          72      17              4            2     3D  1463.6 -1290.2  14.0   3  20200812-CardiomyocyteDifferentiation14-Cycle1...
163510  IMG  2020-08-13T03:20:16.312+02:00       8    7          1          72      18              4            2     3D  1463.6 -1290.2  15.0   3  20200812-CardiomyocyteDifferentiation14-Cycle1...
163511  IMG  2020-08-13T03:20:16.494+02:00       8    7          1          72      19              4            2     3D  1463.6 -1290.2  16.0   3  20200812-CardiomyocyteDifferentiation14-Cycle1...

[163512 rows x 15 columns]
```

We should then verify whether the bottleneck is in this part or in the rest of the function. Our guess is that the loop
```python
    for idx, record in enumerate(mlf_entries):
```
is not efficient, and that handling the dataframe directly from pandas would be better.

**Comment by jluethi** [comment]
Yes, I also started looking at that. It also looks like that loop is the issue to me and the pandas reading looks like the solution.

I will have a look later into refactoring this, but I'd say this is not the most urgent bug to fix. It's not blocking to any of our current milestones, just makes scaling to very large datasets very slow for the moment.

**Comment by jluethi** [comment]
Unless you already started a refactor, think this will go fast and want to dive into this, then go ahead. Just remember that we'll need to invert the Y axis (happens in that loop).

**Comment by tcompa** [comment]
I don't have an implementation ready, let's postpone it a bit.

**Comment by jluethi** [comment]
This may be much less of an issue than expected. Ran the 23 well dataset on the Pelkmans lab cluster now. This was the performance:
Looks like the metadata parsing ran in 4 minutes. It's part of the "Create OME-ZARR structure" task after all

```
2022-09-27 19:37:18,626; INFO; ********************************************************************************
2022-09-27 19:37:18,626; INFO; fractal_server.__VERSION__: 0.1.4
2022-09-27 19:37:18,626; INFO; Start workflow WF 23 well
2022-09-27 19:37:18,626; INFO; input_paths=[PosixPath('/data/active/jluethi/20200810-CardiomyocyteDifferentiation14/Cycle1/images_renamed/*.png')]
2022-09-27 19:37:18,626; INFO; output_path=PosixPath('/data/active/jluethi/Fractal/20220927_23well_Cardiomyocytes/*.zarr')
2022-09-27 19:37:18,626; INFO; settings.PARSL_CONFIG='pelkmanslab'
2022-09-27 19:37:18,626; INFO; settings.PARSL_DEFAULT_EXECUTOR='cpu-low'
2022-09-27 19:37:18,629; INFO; DFK probably missing, proceed with parsl.clear and parsl.config.Config
2022-09-27 19:37:18,878; INFO; DFK <parsl.dataflow.dflow.DataFlowKernel object at 0x7f767153fee0> now has 5 executors: ['9___cpu-low', '9___cpu-mid', '9___cpu-high', '9___gpu', '_parsl_internal']
2022-09-27 19:37:18,893; INFO; Starting "Create OME-ZARR structure" task on "9___cpu-mid" executor.
2022-09-27 19:41:21,238; INFO; Starting "Yokogawa to Zarr" task on "9___cpu-mid" executor.
2022-09-28 00:18:55,991; INFO; Starting "Illumination correction" task on "9___cpu-mid" executor.
2022-09-28 07:23:49,061; INFO; Starting "Replicate Zarr structure" task on "9___cpu-mid" executor.
2022-09-28 07:24:13,680; INFO; Starting "Maximum Intensity Projection" task on "9___cpu-mid" executor.
2022-09-28 09:23:51,527; INFO; Starting "Per-FOV image labeling" task on "9___cpu-high" executor.
```

**Comment by jluethi** [comment]
Refactor is done with https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/136
Performance was ok (but somewhat slow) during actual runs. But especially for debugging issues like https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/110, the faster performance is a big help. And the refactor seems to have solved part of that issue (though now something else came up there).
