### ISSUE TITLE
ROI bounding box

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#99]
From https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/16:

> Can you open a separate issue for the get_ROIs_bounding_box discussion? Not sure I follow why there would be different functions for well & FOV (and later also organoids?). Couldn't a refactored function then just use the ROI_table_name input, then process the corresponding table?
> Also, let's use that issue to get away again from the index-based accessing of ROI positions. That's fine for internal use (e.g. for getting to the demo), but we'll want to generalize that eventually :)

Current status:
* We parse FOV metadata and construct a pandas dataframe (`parse_yokogawa_metadata`).
* We use `prepare_FOV_ROI_table` (based on the dataframe) to construct the FOV anndata table (in `create_zarr_structure`).
* We use `prepare_well_ROI_table` (based on the dataframe) to construct the well anndata table (in `create_zarr_structure`).
* The last two functions can be easily combined into one, as they share a large common part, but they also do different things. The "well" one essentially has to find the bounding box (in micrometers), which is what defines a well ROI.
* Other tasks (especially `image_labeling`, but perhaps also others in the future) can take a free parameter like `ROI_table_name`, pointing to a specific subgroup of `tables` to be used.
* `convert_ROI_table_to_indices` work in the same way with well/FOV/... inputs. It just takes a ROI and gives back the indices.

What I referred to in the other issue is the following:
In the previous version, we used `get_ROIs_bounding_box`, and we had included the logic for specifying the column names to be used (although this was not yet exposed to the user). In the new version, this decision is shifted to earlier steps, namely to the two `prepare_{FOV,well}_ROI_table` functions. If we want some flexibility on column names, we should put it in there (rather than downstream, at the point where we need to know the well size to build a zarr).

**Comment by jluethi** [comment]
> In the new version, this decision is shifted to earlier steps, namely to the two prepare_{FOV,well}_ROI_table functions. If we want some flexibility on column names, we should put it in there (rather than downstream, at the point where we need to know the well size to build a zarr).

Having the flexibility upstream is nice, but Fractal can run quite standardized on that. The flexibility I was mostly concerned about was some user bringing in an OME-Zarr file with ROIs that follow our standard (e.g. having corner position & extent in physical units), but having the order of those columns be different. Given that Fractal should handle OME-Zarr files in general and I hope the ROI standard becomes more generally used in OME-Zarrs, we should be flexible in reading them.

Not an urgent issue though, let's first make sure the "all Fractal" workflows work well :)

**Comment by jluethi** [comment]
Given the discussion in https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/91, we may switch to having additional metadata in the ROI table (e.g. original positions & adapted positions) => would be important that we have a good way of choosing the right columns that isn't index-depending

**Comment by tcompa** [comment]
Ref https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/106/commits/8e3aa4fd8e73befe718fa36002018b609d9c97d9

We now expose the column names as arguments of `convert_ROI_table_to_indices`. Depending on where we'll want to use them, we'll have to modify some tasks.
